<?php

class MunicipioTableSeeder extends Seeder {

    public function run() {
        $municipios = [
            ['estado_id' => 1, 'nombre' => 'CE. BLVNO LIBERTADOR'],
            ['estado_id' => 2, 'nombre' => 'MP. ANACO'],
            ['estado_id' => 2, 'nombre' => 'MP. ARAGUA'],
            ['estado_id' => 2, 'nombre' => 'CE. BOLIVAR'],
            ['estado_id' => 2, 'nombre' => 'MP. BRUZUAL'],
            ['estado_id' => 2, 'nombre' => 'MP. CAJIGAL'],
            ['estado_id' => 2, 'nombre' => 'MP. FREITES'],
            ['estado_id' => 2, 'nombre' => 'MP. INDEPENDENCIA'],
            ['estado_id' => 2, 'nombre' => 'MP. LIBERTAD'],
            ['estado_id' => 2, 'nombre' => 'MP. MIRANDA'],
            ['estado_id' => 2, 'nombre' => 'MP. MONAGAS'],
            ['estado_id' => 2, 'nombre' => 'MP. PEÑALVER'],
            ['estado_id' => 2, 'nombre' => 'MP. SIMON RODRIGUEZ'],
            ['estado_id' => 2, 'nombre' => 'MP. SOTILLO'],
            ['estado_id' => 2, 'nombre' => 'MP. GUANIPA'],
            ['estado_id' => 2, 'nombre' => 'MP. GUANTA'],
            ['estado_id' => 2, 'nombre' => 'MP. PIRITU'],
            ['estado_id' => 2, 'nombre' => 'MP. L/DIEGO BAUTISTA'],
            ['estado_id' => 2, 'nombre' => 'MP. CARVAJAL'],
            ['estado_id' => 2, 'nombre' => 'MP. SANTA ANA'],
            ['estado_id' => 2, 'nombre' => 'MP. MC GREGOR'],
            ['estado_id' => 2, 'nombre' => 'MP. S JUAN CAPISTRANO'],
            ['estado_id' => 3, 'nombre' => 'MP. ACHAGUAS'],
            ['estado_id' => 3, 'nombre' => 'MP. MUÑOZ'],
            ['estado_id' => 3, 'nombre' => 'MP. PAEZ'],
            ['estado_id' => 3, 'nombre' => 'MP. PEDRO CAMEJO'],
            ['estado_id' => 3, 'nombre' => 'MP. ROMULO GALLEGOS'],
            ['estado_id' => 3, 'nombre' => 'CE. SAN FERNANDO'],
            ['estado_id' => 3, 'nombre' => 'MP. BIRUACA'],
            ['estado_id' => 4, 'nombre' => 'CE. GIRARDOT'],
            ['estado_id' => 4, 'nombre' => 'MP. SANTIAGO MARIÑO'],
            ['estado_id' => 4, 'nombre' => 'MP. JOSE FELIX RIVAS'],
            ['estado_id' => 4, 'nombre' => 'MP. SAN CASIMIRO'],
            ['estado_id' => 4, 'nombre' => 'MP. SAN SEBASTIAN'],
            ['estado_id' => 4, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 4, 'nombre' => 'MP. URDANETA'],
            ['estado_id' => 4, 'nombre' => 'MP. ZAMORA'],
            ['estado_id' => 4, 'nombre' => 'MP. LIBERTADOR'],
            ['estado_id' => 4, 'nombre' => 'MP. JOSE ANGEL LAMAS'],
            ['estado_id' => 4, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 4, 'nombre' => 'MP. SANTOS MICHELENA'],
            ['estado_id' => 4, 'nombre' => 'MP. MARIO B IRAGORRY'],
            ['estado_id' => 4, 'nombre' => 'MP. TOVAR'],
            ['estado_id' => 4, 'nombre' => 'MP. CAMATAGUA'],
            ['estado_id' => 4, 'nombre' => 'MP. JOSE R REVENGA'],
            ['estado_id' => 4, 'nombre' => 'MP. FRANCISCO LINARES'],
            ['estado_id' => 4, 'nombre' => 'MP. OCUMARE D L COSTA'],
            ['estado_id' => 5, 'nombre' => 'MP. ARISMENDI'],
            ['estado_id' => 5, 'nombre' => 'CE. BARINAS'],
            ['estado_id' => 5, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 5, 'nombre' => 'MP. EZEQUIEL ZAMORA'],
            ['estado_id' => 5, 'nombre' => 'MP. OBISPOS'],
            ['estado_id' => 5, 'nombre' => 'MP. PEDRAZA'],
            ['estado_id' => 5, 'nombre' => 'MP. ROJAS'],
            ['estado_id' => 5, 'nombre' => 'MP. SOSA'],
            ['estado_id' => 5, 'nombre' => 'MP. ALBERTO ARVELO T'],
            ['estado_id' => 5, 'nombre' => 'MP. A JOSE DE SUCRE'],
            ['estado_id' => 5, 'nombre' => 'MP. CRUZ PAREDES'],
            ['estado_id' => 5, 'nombre' => 'MP. ANDRES E. BLANCO'],
            ['estado_id' => 6, 'nombre' => 'MP. CARONI'],
            ['estado_id' => 6, 'nombre' => 'MP. CEDEÑO'],
            ['estado_id' => 6, 'nombre' => 'CE. HERES'],
            ['estado_id' => 6, 'nombre' => 'MP. PIAR'],
            ['estado_id' => 6, 'nombre' => 'MP. ROSCIO'],
            ['estado_id' => 6, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 6, 'nombre' => 'MP. SIFONTES'],
            ['estado_id' => 6, 'nombre' => 'MP. BLVNO ANGOSTURA'],
            ['estado_id' => 6, 'nombre' => 'MP. GRAN SABANA'],
            ['estado_id' => 6, 'nombre' => 'MP. EL CALLAO'],
            ['estado_id' => 6, 'nombre' => 'MP. PADRE PEDRO CHIEN'],
            ['estado_id' => 7, 'nombre' => 'MP. BEJUMA'],
            ['estado_id' => 7, 'nombre' => 'MP. CARLOS ARVELO'],
            ['estado_id' => 7, 'nombre' => 'MP. DIEGO IBARRA'],
            ['estado_id' => 7, 'nombre' => 'MP. GUACARA'],
            ['estado_id' => 7, 'nombre' => 'MP. MONTALBAN'],
            ['estado_id' => 7, 'nombre' => 'MP. JUAN JOSE MORA'],
            ['estado_id' => 7, 'nombre' => 'MP. PUERTO CABELLO'],
            ['estado_id' => 7, 'nombre' => 'MP. SAN JOAQUIN'],
            ['estado_id' => 7, 'nombre' => 'CE. VALENCIA'],
            ['estado_id' => 7, 'nombre' => 'MP. MIRANDA'],
            ['estado_id' => 7, 'nombre' => 'MP. LOS GUAYOS'],
            ['estado_id' => 7, 'nombre' => 'MP. NAGUANAGUA'],
            ['estado_id' => 7, 'nombre' => 'MP. SAN DIEGO'],
            ['estado_id' => 7, 'nombre' => 'MP. LIBERTADOR'],
            ['estado_id' => 8, 'nombre' => 'MP. ANZOATEGUI'],
            ['estado_id' => 8, 'nombre' => 'MP. FALCON'],
            ['estado_id' => 8, 'nombre' => 'MP. GIRARDOT'],
            ['estado_id' => 8, 'nombre' => 'MP. PAO S J BAUTISTA'],
            ['estado_id' => 8, 'nombre' => 'MP. RICAURTE'],
            ['estado_id' => 8, 'nombre' => 'CE. EZEQUIEL ZAMORA'],
            ['estado_id' => 8, 'nombre' => 'MP. TINACO'],
            ['estado_id' => 8, 'nombre' => 'MP. LIMA BLANCO'],
            ['estado_id' => 8, 'nombre' => 'MP. ROMULO GALLEGOS'],
            ['estado_id' => 9, 'nombre' => 'MP. ACOSTA'],
            ['estado_id' => 9, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 9, 'nombre' => 'MP. BUCHIVACOA'],
            ['estado_id' => 9, 'nombre' => 'MP. CARIRUBANA'],
            ['estado_id' => 9, 'nombre' => 'MP. COLINA'],
            ['estado_id' => 9, 'nombre' => 'MP. DEMOCRACIA'],
            ['estado_id' => 9, 'nombre' => 'MP. FALCON'],
            ['estado_id' => 9, 'nombre' => 'MP. FEDERACION'],
            ['estado_id' => 9, 'nombre' => 'MP. MAUROA'],
            ['estado_id' => 9, 'nombre' => 'CE. MIRANDA'],
            ['estado_id' => 9, 'nombre' => 'MP. PETIT'],
            ['estado_id' => 9, 'nombre' => 'MP. SILVA'],
            ['estado_id' => 9, 'nombre' => 'MP. ZAMORA'],
            ['estado_id' => 9, 'nombre' => 'MP. DABAJURO'],
            ['estado_id' => 9, 'nombre' => 'MP. MONS. ITURRIZA'],
            ['estado_id' => 9, 'nombre' => 'MP. LOS TAQUES'],
            ['estado_id' => 9, 'nombre' => 'MP. PIRITU'],
            ['estado_id' => 9, 'nombre' => 'MP. UNION'],
            ['estado_id' => 9, 'nombre' => 'MP. SAN FRANCISCO'],
            ['estado_id' => 9, 'nombre' => 'MP. JACURA'],
            ['estado_id' => 9, 'nombre' => 'MP. CACIQUE MANAURE'],
            ['estado_id' => 9, 'nombre' => 'MP. PALMA SOLA'],
            ['estado_id' => 9, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 9, 'nombre' => 'MP. URUMACO'],
            ['estado_id' => 9, 'nombre' => 'MP. TOCOPERO'],
            ['estado_id' => 10, 'nombre' => 'MP. INFANTE'],
            ['estado_id' => 10, 'nombre' => 'MP. MELLADO'],
            ['estado_id' => 10, 'nombre' => 'MP. MIRANDA'],
            ['estado_id' => 10, 'nombre' => 'MP. MONAGAS'],
            ['estado_id' => 10, 'nombre' => 'MP. RIBAS'],
            ['estado_id' => 10, 'nombre' => 'CE. ROSCIO'],
            ['estado_id' => 10, 'nombre' => 'MP. ZARAZA'],
            ['estado_id' => 10, 'nombre' => 'MP. CAMAGUAN'],
            ['estado_id' => 10, 'nombre' => 'MP. S JOSE DE GUARIBE'],
            ['estado_id' => 10, 'nombre' => 'MP. LAS MERCEDES'],
            ['estado_id' => 10, 'nombre' => 'MP. EL SOCORRO'],
            ['estado_id' => 10, 'nombre' => 'MP. ORTIZ'],
            ['estado_id' => 10, 'nombre' => 'MP. S MARIA DE IPIRE'],
            ['estado_id' => 10, 'nombre' => 'MP. CHAGUARAMAS'],
            ['estado_id' => 10, 'nombre' => 'MP. SAN GERONIMO DE G'],
            ['estado_id' => 11, 'nombre' => 'MP. CRESPO'],
            ['estado_id' => 11, 'nombre' => 'CE. IRIBARREN'],
            ['estado_id' => 11, 'nombre' => 'MP. JIMENEZ'],
            ['estado_id' => 11, 'nombre' => 'MP. MORAN'],
            ['estado_id' => 11, 'nombre' => 'MP. PALAVECINO'],
            ['estado_id' => 11, 'nombre' => 'MP. TORRES'],
            ['estado_id' => 11, 'nombre' => 'MP. URDANETA'],
            ['estado_id' => 11, 'nombre' => 'MP. ANDRES E BLANCO'],
            ['estado_id' => 11, 'nombre' => 'MP. SIMON PLANAS'],
            ['estado_id' => 12, 'nombre' => 'MP. ALBERTO ADRIANI'],
            ['estado_id' => 12, 'nombre' => 'MP. ANDRES BELLO'],
            ['estado_id' => 12, 'nombre' => 'MP. ARZOBISPO CHACON'],
            ['estado_id' => 12, 'nombre' => 'MP. CAMPO ELIAS'],
            ['estado_id' => 12, 'nombre' => 'MP. GUARAQUE'],
            ['estado_id' => 12, 'nombre' => 'MP. JULIO CESAR SALAS'],
            ['estado_id' => 12, 'nombre' => 'MP. JUSTO BRICEÑO'],
            ['estado_id' => 12, 'nombre' => 'CE. LIBERTADOR'],
            ['estado_id' => 12, 'nombre' => 'MP. SANTOS MARQUINA'],
            ['estado_id' => 12, 'nombre' => 'MP. MIRANDA'],
            ['estado_id' => 12, 'nombre' => 'MP. ANTONIO PINTO S.'],
            ['estado_id' => 12, 'nombre' => 'MP. OB. RAMOS DE LORA'],
            ['estado_id' => 12, 'nombre' => 'MP. CARACCIOLO PARRA'],
            ['estado_id' => 12, 'nombre' => 'MP. CARDENAL QUINTERO'],
            ['estado_id' => 12, 'nombre' => 'MP. PUEBLO LLANO'],
            ['estado_id' => 12, 'nombre' => 'MP. RANGEL'],
            ['estado_id' => 12, 'nombre' => 'MP. RIVAS DAVILA'],
            ['estado_id' => 12, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 12, 'nombre' => 'MP. TOVAR'],
            ['estado_id' => 12, 'nombre' => 'MP. TULIO F CORDERO'],
            ['estado_id' => 12, 'nombre' => 'MP. PADRE NOGUERA'],
            ['estado_id' => 12, 'nombre' => 'MP. ARICAGUA'],
            ['estado_id' => 12, 'nombre' => 'MP. ZEA'],
            ['estado_id' => 13, 'nombre' => 'MP. ACEVEDO'],
            ['estado_id' => 13, 'nombre' => 'MP. BRION'],
            ['estado_id' => 13, 'nombre' => 'CE. GUAICAIPURO'],
            ['estado_id' => 13, 'nombre' => 'MP. INDEPENDENCIA'],
            ['estado_id' => 13, 'nombre' => 'MP. LANDER'],
            ['estado_id' => 13, 'nombre' => 'MP. PAEZ'],
            ['estado_id' => 13, 'nombre' => 'MP. PAZ CASTILLO'],
            ['estado_id' => 13, 'nombre' => 'MP. PLAZA'],
            ['estado_id' => 13, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 13, 'nombre' => 'MP. URDANETA'],
            ['estado_id' => 13, 'nombre' => 'MP. ZAMORA'],
            ['estado_id' => 13, 'nombre' => 'MP. CRISTOBAL ROJAS'],
            ['estado_id' => 13, 'nombre' => 'MP. LOS SALIAS'],
            ['estado_id' => 13, 'nombre' => 'MP. ANDRES BELLO'],
            ['estado_id' => 13, 'nombre' => 'MP. SIMON BOLIVAR'],
            ['estado_id' => 13, 'nombre' => 'MP. BARUTA'],
            ['estado_id' => 13, 'nombre' => 'MP. CARRIZAL'],
            ['estado_id' => 13, 'nombre' => 'MP. CHACAO'],
            ['estado_id' => 13, 'nombre' => 'MP. EL HATILLO'],
            ['estado_id' => 13, 'nombre' => 'MP. BUROZ'],
            ['estado_id' => 13, 'nombre' => 'MP. PEDRO GUAL'],
            ['estado_id' => 14, 'nombre' => 'MP. ACOSTA'],
            ['estado_id' => 14, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 14, 'nombre' => 'MP. CARIPE'],
            ['estado_id' => 14, 'nombre' => 'MP. CEDEÑO'],
            ['estado_id' => 14, 'nombre' => 'MP. EZEQUIEL ZAMORA'],
            ['estado_id' => 14, 'nombre' => 'MP. LIBERTADOR'],
            ['estado_id' => 14, 'nombre' => 'CE. MATURIN'],
            ['estado_id' => 14, 'nombre' => 'MP. PIAR'],
            ['estado_id' => 14, 'nombre' => 'MP. PUNCERES'],
            ['estado_id' => 14, 'nombre' => 'MP. SOTILLO'],
            ['estado_id' => 14, 'nombre' => 'MP. AGUASAY'],
            ['estado_id' => 14, 'nombre' => 'MP. SANTA BARBARA'],
            ['estado_id' => 14, 'nombre' => 'MP. URACOA'],
            ['estado_id' => 15, 'nombre' => 'CE. ARISMENDI'],
            ['estado_id' => 15, 'nombre' => 'MP. DIAZ'],
            ['estado_id' => 15, 'nombre' => 'MP. GOMEZ'],
            ['estado_id' => 15, 'nombre' => 'MP. MANEIRO'],
            ['estado_id' => 15, 'nombre' => 'MP. MARCANO'],
            ['estado_id' => 15, 'nombre' => 'MP. MARIÑO'],
            ['estado_id' => 15, 'nombre' => 'MP. PENIN. DE MACANAO'],
            ['estado_id' => 15, 'nombre' => 'MP. VILLALBA(I.COCHE)'],
            ['estado_id' => 15, 'nombre' => 'MP. TUBORES'],
            ['estado_id' => 15, 'nombre' => 'MP. ANTOLIN DEL CAMPO'],
            ['estado_id' => 15, 'nombre' => 'MP. GARCIA'],
            ['estado_id' => 16, 'nombre' => 'MP. ARAURE'],
            ['estado_id' => 16, 'nombre' => 'MP. ESTELLER'],
            ['estado_id' => 16, 'nombre' => 'CE. GUANARE'],
            ['estado_id' => 16, 'nombre' => 'MP. GUANARITO'],
            ['estado_id' => 16, 'nombre' => 'MP. OSPINO'],
            ['estado_id' => 16, 'nombre' => 'MP. PAEZ'],
            ['estado_id' => 16, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 16, 'nombre' => 'MP. TUREN'],
            ['estado_id' => 16, 'nombre' => 'MP. M.JOSE V DE UNDA'],
            ['estado_id' => 16, 'nombre' => 'MP. AGUA BLANCA'],
            ['estado_id' => 16, 'nombre' => 'MP. PAPELON'],
            ['estado_id' => 16, 'nombre' => 'MP. GENARO BOCONOITO'],
            ['estado_id' => 16, 'nombre' => 'MP. S RAFAEL DE ONOTO'],
            ['estado_id' => 16, 'nombre' => 'MP. SANTA ROSALIA'],
            ['estado_id' => 17, 'nombre' => 'MP. ARISMENDI'],
            ['estado_id' => 17, 'nombre' => 'MP. BENITEZ'],
            ['estado_id' => 17, 'nombre' => 'MP. BERMUDEZ'],
            ['estado_id' => 17, 'nombre' => 'MP. CAJIGAL'],
            ['estado_id' => 17, 'nombre' => 'MP. MARIÑO'],
            ['estado_id' => 17, 'nombre' => 'MP. MEJIA'],
            ['estado_id' => 17, 'nombre' => 'MP. MONTES'],
            ['estado_id' => 17, 'nombre' => 'MP. RIBERO'],
            ['estado_id' => 17, 'nombre' => 'CE. SUCRE'],
            ['estado_id' => 17, 'nombre' => 'MP. VALDEZ'],
            ['estado_id' => 17, 'nombre' => 'MP. ANDRES E BLANCO'],
            ['estado_id' => 17, 'nombre' => 'MP. LIBERTADOR'],
            ['estado_id' => 17, 'nombre' => 'MP. ANDRES MATA'],
            ['estado_id' => 17, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 17, 'nombre' => 'MP. CRUZ S ACOSTA'],
            ['estado_id' => 18, 'nombre' => 'MP. AYACUCHO'],
            ['estado_id' => 18, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 18, 'nombre' => 'MP. INDEPENDENCIA'],
            ['estado_id' => 18, 'nombre' => 'MP. CARDENAS'],
            ['estado_id' => 18, 'nombre' => 'MP. JAUREGUI'],
            ['estado_id' => 18, 'nombre' => 'MP. JUNIN'],
            ['estado_id' => 18, 'nombre' => 'MP. LOBATERA'],
            ['estado_id' => 18, 'nombre' => 'CE. SAN CRISTOBAL'],
            ['estado_id' => 18, 'nombre' => 'MP. URIBANTE'],
            ['estado_id' => 18, 'nombre' => 'MP. CORDOBA'],
            ['estado_id' => 18, 'nombre' => 'MP. GARCIA DE HEVIA'],
            ['estado_id' => 18, 'nombre' => 'MP. GUASIMOS'],
            ['estado_id' => 18, 'nombre' => 'MP. MICHELENA'],
            ['estado_id' => 18, 'nombre' => 'MP. LIBERTADOR'],
            ['estado_id' => 18, 'nombre' => 'MP. PANAMERICANO'],
            ['estado_id' => 18, 'nombre' => 'MP. PEDRO MARIA UREÑA'],
            ['estado_id' => 18, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 18, 'nombre' => 'MP. ANDRES BELLO'],
            ['estado_id' => 18, 'nombre' => 'MP. FERNANDEZ FEO'],
            ['estado_id' => 18, 'nombre' => 'MP. LIBERTAD'],
            ['estado_id' => 18, 'nombre' => 'MP. SAMUEL MALDONADO'],
            ['estado_id' => 18, 'nombre' => 'MP. SEBORUCO'],
            ['estado_id' => 18, 'nombre' => 'MP. ANTONIO ROMULO C'],
            ['estado_id' => 18, 'nombre' => 'MP. FCO DE MIRANDA'],
            ['estado_id' => 18, 'nombre' => 'MP. JOSE MARIA VARGA'],
            ['estado_id' => 18, 'nombre' => 'MP. RAFAEL URDANETA'],
            ['estado_id' => 18, 'nombre' => 'MP. SIMON RODRIGUEZ'],
            ['estado_id' => 18, 'nombre' => 'MP. TORBES'],
            ['estado_id' => 18, 'nombre' => 'MP. SAN JUDAS TADEO'],
            ['estado_id' => 19, 'nombre' => 'MP. RAFAEL RANGEL'],
            ['estado_id' => 19, 'nombre' => 'MP. BOCONO'],
            ['estado_id' => 19, 'nombre' => 'MP. CARACHE'],
            ['estado_id' => 19, 'nombre' => 'MP. ESCUQUE'],
            ['estado_id' => 19, 'nombre' => 'CE. TRUJILLO'],
            ['estado_id' => 19, 'nombre' => 'MP. URDANETA'],
            ['estado_id' => 19, 'nombre' => 'MP. VALERA'],
            ['estado_id' => 19, 'nombre' => 'MP. CANDELARIA'],
            ['estado_id' => 19, 'nombre' => 'MP. MIRANDA'],
            ['estado_id' => 19, 'nombre' => 'MP. MONTE CARMELO'],
            ['estado_id' => 19, 'nombre' => 'MP. MOTATAN'],
            ['estado_id' => 19, 'nombre' => 'MP. PAMPAN'],
            ['estado_id' => 19, 'nombre' => 'MP. S RAFAEL CARVAJAL'],
            ['estado_id' => 19, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 19, 'nombre' => 'MP. ANDRES BELLO'],
            ['estado_id' => 19, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 19, 'nombre' => 'MP. JOSE F M CAÑIZAL'],
            ['estado_id' => 19, 'nombre' => 'MP. JUAN V CAMPO ELI'],
            ['estado_id' => 19, 'nombre' => 'MP. LA CEIBA'],
            ['estado_id' => 19, 'nombre' => 'MP. PAMPANITO'],
            ['estado_id' => 20, 'nombre' => 'MP. BOLIVAR'],
            ['estado_id' => 20, 'nombre' => 'MP. BRUZUAL'],
            ['estado_id' => 20, 'nombre' => 'MP. NIRGUA'],
            ['estado_id' => 20, 'nombre' => 'CE. SAN FELIPE'],
            ['estado_id' => 20, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 20, 'nombre' => 'MP. URACHICHE'],
            ['estado_id' => 20, 'nombre' => 'MP. PEÑA'],
            ['estado_id' => 20, 'nombre' => 'MP. JOSE ANTONIO PAEZ'],
            ['estado_id' => 20, 'nombre' => 'MP. LA TRINIDAD'],
            ['estado_id' => 20, 'nombre' => 'MP. COCOROTE'],
            ['estado_id' => 20, 'nombre' => 'MP. INDEPENDENCIA'],
            ['estado_id' => 20, 'nombre' => 'MP. ARISTIDES BASTID'],
            ['estado_id' => 20, 'nombre' => 'MP. MANUEL MONGE'],
            ['estado_id' => 20, 'nombre' => 'MP. VEROES'],
            ['estado_id' => 21, 'nombre' => 'MP. BARALT'],
            ['estado_id' => 21, 'nombre' => 'MP. SANTA RITA'],
            ['estado_id' => 21, 'nombre' => 'MP. COLON'],
            ['estado_id' => 21, 'nombre' => 'MP. MARA'],
            ['estado_id' => 21, 'nombre' => 'CE. MARACAIBO'],
            ['estado_id' => 21, 'nombre' => 'MP. MIRANDA'],
            ['estado_id' => 21, 'nombre' => 'MP. IDJ BLVNO GUAJIRA'],
            ['estado_id' => 21, 'nombre' => 'MP. MACHIQUES DE P'],
            ['estado_id' => 21, 'nombre' => 'MP. SUCRE'],
            ['estado_id' => 21, 'nombre' => 'MP. LA CAÑADA DE U.'],
            ['estado_id' => 21, 'nombre' => 'MP. LAGUNILLAS'],
            ['estado_id' => 21, 'nombre' => 'MP. CATATUMBO'],
            ['estado_id' => 21, 'nombre' => 'MP. ROSARIO DE PERIJA'],
            ['estado_id' => 21, 'nombre' => 'MP. CABIMAS'],
            ['estado_id' => 21, 'nombre' => 'MP. VALMORE RODRIGUEZ'],
            ['estado_id' => 21, 'nombre' => 'MP. JESUS E LOSSADA'],
            ['estado_id' => 21, 'nombre' => 'MP. ALMIRANTE P'],
            ['estado_id' => 21, 'nombre' => 'MP. SAN FRANCISCO'],
            ['estado_id' => 21, 'nombre' => 'MP. JESUS M SEMPRUN'],
            ['estado_id' => 21, 'nombre' => 'MP. FRANCISCO J PULG'],
            ['estado_id' => 21, 'nombre' => 'MP. SIMON BOLIVAR'],
            ['estado_id' => 22, 'nombre' => 'CE. ATURES'],
            ['estado_id' => 22, 'nombre' => 'MP. ATABAPO'],
            ['estado_id' => 22, 'nombre' => 'MP. MAROA'],
            ['estado_id' => 22, 'nombre' => 'MP. RIO NEGRO'],
            ['estado_id' => 22, 'nombre' => 'MP. AUTANA'],
            ['estado_id' => 22, 'nombre' => 'MP. MANAPIARE'],
            ['estado_id' => 22, 'nombre' => 'MP. ALTO ORINOCO'],
            ['estado_id' => 23, 'nombre' => 'CE. TUCUPITA'],
            ['estado_id' => 23, 'nombre' => 'MP. PEDERNALES'],
            ['estado_id' => 23, 'nombre' => 'MP. ANTONIO DIAZ'],
            ['estado_id' => 23, 'nombre' => 'MP. CASACOIMA'],
            ['estado_id' => 24, 'nombre' => 'CE. VARGAS'],
        ];
        foreach ($municipios as $municipio) {
            Municipio::create($municipio);
        }
    }

}
