<?php

class ParroquiaTableSeeder extends Seeder {

    public function run() {
        $parroquias = [
            ['municipio_id' => 1, 'nombre' => 'PQ. ALTAGRACIA'],
            ['municipio_id' => 1, 'nombre' => 'PQ. CANDELARIA'],
            ['municipio_id' => 1, 'nombre' => 'PQ. CATEDRAL'],
            ['municipio_id' => 1, 'nombre' => 'PQ. LA PASTORA'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SAN AGUSTIN'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SAN JUAN'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SANTA ROSALIA'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SANTA TERESA'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SUCRE'],
            ['municipio_id' => 1, 'nombre' => 'PQ. 23 DE ENERO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. ANTIMANO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. EL RECREO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. EL VALLE'],
            ['municipio_id' => 1, 'nombre' => 'PQ. LA VEGA'],
            ['municipio_id' => 1, 'nombre' => 'PQ. MACARAO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. CARICUAO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. EL JUNQUITO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. COCHE'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SAN PEDRO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. SAN BERNARDINO'],
            ['municipio_id' => 1, 'nombre' => 'PQ. EL PARAISO'],
            ['municipio_id' => 2, 'nombre' => 'PQ. ANACO'],
            ['municipio_id' => 2, 'nombre' => 'PQ. SAN JOAQUIN'],
            ['municipio_id' => 3, 'nombre' => 'CM. ARAGUA DE BARCELONA'],
            ['municipio_id' => 3, 'nombre' => 'PQ. CACHIPO'],
            ['municipio_id' => 4, 'nombre' => 'PQ. EL CARMEN'],
            ['municipio_id' => 4, 'nombre' => 'PQ. SAN CRISTOBAL'],
            ['municipio_id' => 4, 'nombre' => 'PQ. BERGANTIN'],
            ['municipio_id' => 4, 'nombre' => 'PQ. CAIGUA'],
            ['municipio_id' => 4, 'nombre' => 'PQ. EL PILAR'],
            ['municipio_id' => 4, 'nombre' => 'PQ. NARICUAL'],
            ['municipio_id' => 5, 'nombre' => 'CM. CLARINES'],
            ['municipio_id' => 5, 'nombre' => 'PQ. GUANAPE'],
            ['municipio_id' => 5, 'nombre' => 'PQ. SABANA DE UCHIRE'],
            ['municipio_id' => 6, 'nombre' => 'CM. ONOTO'],
            ['municipio_id' => 6, 'nombre' => 'PQ. SAN PABLO'],
            ['municipio_id' => 7, 'nombre' => 'CM. CANTAURA'],
            ['municipio_id' => 7, 'nombre' => 'PQ. LIBERTADOR'],
            ['municipio_id' => 7, 'nombre' => 'PQ. SANTA ROSA'],
            ['municipio_id' => 7, 'nombre' => 'PQ. URICA'],
            ['municipio_id' => 8, 'nombre' => 'CM. SOLEDAD'],
            ['municipio_id' => 8, 'nombre' => 'PQ. MAMO'],
            ['municipio_id' => 9, 'nombre' => 'CM. SAN MATEO'],
            ['municipio_id' => 9, 'nombre' => 'PQ. EL CARITO'],
            ['municipio_id' => 9, 'nombre' => 'PQ. SANTA INES'],
            ['municipio_id' => 10, 'nombre' => 'CM. PARIAGUAN'],
            ['municipio_id' => 10, 'nombre' => 'PQ. ATAPIRIRE'],
            ['municipio_id' => 10, 'nombre' => 'PQ. BOCA DEL PAO'],
            ['municipio_id' => 10, 'nombre' => 'PQ. EL PAO'],
            ['municipio_id' => 11, 'nombre' => 'CM. MAPIRE'],
            ['municipio_id' => 11, 'nombre' => 'PQ. PIAR'],
            ['municipio_id' => 11, 'nombre' => 'PQ. SN DIEGO DE CABRUTICA'],
            ['municipio_id' => 11, 'nombre' => 'PQ. SANTA CLARA'],
            ['municipio_id' => 11, 'nombre' => 'PQ. UVERITO'],
            ['municipio_id' => 11, 'nombre' => 'PQ. ZUATA'],
            ['municipio_id' => 12, 'nombre' => 'CM. PUERTO PIRITU'],
            ['municipio_id' => 12, 'nombre' => 'PQ. SAN MIGUEL'],
            ['municipio_id' => 12, 'nombre' => 'PQ. SUCRE'],
            ['municipio_id' => 13, 'nombre' => 'CM. EL TIGRE'],
            ['municipio_id' => 14, 'nombre' => 'PQ. POZUELOS'],
            ['municipio_id' => 14, 'nombre' => 'CM. PUERTO LA CRUZ'],
            ['municipio_id' => 15, 'nombre' => 'CM. SAN JOSE DE GUANIPA'],
            ['municipio_id' => 16, 'nombre' => 'PQ. GUANTA'],
            ['municipio_id' => 16, 'nombre' => 'PQ. CHORRERON'],
            ['municipio_id' => 17, 'nombre' => 'PQ. PIRITU'],
            ['municipio_id' => 17, 'nombre' => 'PQ. SAN FRANCISCO'],
            ['municipio_id' => 18, 'nombre' => 'PQ. LECHERIAS'],
            ['municipio_id' => 18, 'nombre' => 'PQ. EL MORRO'],
            ['municipio_id' => 19, 'nombre' => 'PQ. VALLE GUANAPE'],
            ['municipio_id' => 19, 'nombre' => 'PQ. SANTA BARBARA'],
            ['municipio_id' => 20, 'nombre' => 'PQ. SANTA ANA'],
            ['municipio_id' => 20, 'nombre' => 'PQ. PUEBLO NUEVO'],
            ['municipio_id' => 21, 'nombre' => 'PQ. EL CHAPARRO'],
            ['municipio_id' => 21, 'nombre' => 'PQ. TOMAS ALFARO CALATRAVA'],
            ['municipio_id' => 22, 'nombre' => 'PQ. BOCA UCHIRE'],
            ['municipio_id' => 22, 'nombre' => 'PQ. BOCA DE CHAVEZ'],
            ['municipio_id' => 23, 'nombre' => 'PQ. ACHAGUAS'],
            ['municipio_id' => 23, 'nombre' => 'PQ. APURITO'],
            ['municipio_id' => 23, 'nombre' => 'PQ. EL YAGUAL'],
            ['municipio_id' => 23, 'nombre' => 'PQ. GUACHARA'],
            ['municipio_id' => 23, 'nombre' => 'PQ. MUCURITAS'],
            ['municipio_id' => 23, 'nombre' => 'PQ. QUESERAS DEL MEDIO'],
            ['municipio_id' => 24, 'nombre' => 'PQ. BRUZUAL'],
            ['municipio_id' => 24, 'nombre' => 'PQ. MANTECAL'],
            ['municipio_id' => 24, 'nombre' => 'PQ. QUINTERO'],
            ['municipio_id' => 24, 'nombre' => 'PQ. SAN VICENTE'],
            ['municipio_id' => 24, 'nombre' => 'PQ. RINCON HONDO'],
            ['municipio_id' => 25, 'nombre' => 'PQ. GUASDUALITO'],
            ['municipio_id' => 25, 'nombre' => 'PQ. ARAMENDI'],
            ['municipio_id' => 25, 'nombre' => 'PQ. EL AMPARO'],
            ['municipio_id' => 25, 'nombre' => 'PQ. SAN CAMILO'],
            ['municipio_id' => 25, 'nombre' => 'PQ. URDANETA'],
            ['municipio_id' => 26, 'nombre' => 'PQ. SAN JUAN DE PAYARA'],
            ['municipio_id' => 26, 'nombre' => 'PQ. CODAZZI'],
            ['municipio_id' => 26, 'nombre' => 'PQ. CUNAVICHE'],
            ['municipio_id' => 27, 'nombre' => 'PQ. ELORZA'],
            ['municipio_id' => 27, 'nombre' => 'PQ. LA TRINIDAD'],
            ['municipio_id' => 28, 'nombre' => 'PQ. SAN FERNANDO'],
            ['municipio_id' => 28, 'nombre' => 'PQ. PEÑALVER'],
            ['municipio_id' => 28, 'nombre' => 'PQ. EL RECREO'],
            ['municipio_id' => 28, 'nombre' => 'PQ. SN RAFAEL DE ATAMAICA'],
            ['municipio_id' => 29, 'nombre' => 'PQ. BIRUACA'],
            ['municipio_id' => 30, 'nombre' => 'PQ. LAS DELICIAS'],
            ['municipio_id' => 30, 'nombre' => 'PQ. CHORONI'],
            ['municipio_id' => 30, 'nombre' => 'PQ. MADRE MA DE SAN JOSE'],
            ['municipio_id' => 30, 'nombre' => 'PQ. JOAQUIN CRESPO'],
            ['municipio_id' => 30, 'nombre' => 'PQ. PEDRO JOSE OVALLES'],
            ['municipio_id' => 30, 'nombre' => 'PQ. JOSE CASANOVA GODOY'],
            ['municipio_id' => 30, 'nombre' => 'PQ. ANDRES ELOY BLANCO'],
            ['municipio_id' => 30, 'nombre' => 'PQ. LOS TACARIGUAS'],
            ['municipio_id' => 31, 'nombre' => 'CM. TURMERO'],
            ['municipio_id' => 31, 'nombre' => 'PQ. SAMAN DE GUERE'],
            ['municipio_id' => 31, 'nombre' => 'PQ. ALFREDO PACHECO M'],
            ['municipio_id' => 31, 'nombre' => 'PQ. CHUAO'],
            ['municipio_id' => 31, 'nombre' => 'PQ. AREVALO APONTE'],
            ['municipio_id' => 32, 'nombre' => 'CM. JUAN VICENTE BOLIVAR'],
            ['municipio_id' => 32, 'nombre' => 'PQ. ZUATA'],
            ['municipio_id' => 32, 'nombre' => 'PQ. PAO DE ZARATE'],
            ['municipio_id' => 32, 'nombre' => 'PQ. CASTOR NIEVES RIOS'],
            ['municipio_id' => 32, 'nombre' => 'PQ. LAS GUACAMAYAS'],
            ['municipio_id' => 33, 'nombre' => 'CM. SAN CASIMIRO'],
            ['municipio_id' => 33, 'nombre' => 'PQ. VALLE MORIN'],
            ['municipio_id' => 33, 'nombre' => 'PQ. GUIRIPA'],
            ['municipio_id' => 33, 'nombre' => 'PQ. OLLAS DE CARAMACATE'],
            ['municipio_id' => 34, 'nombre' => 'CM. SAN SEBASTIAN'],
            ['municipio_id' => 35, 'nombre' => 'CM. CAGUA'],
            ['municipio_id' => 35, 'nombre' => 'PQ. BELLA VISTA'],
            ['municipio_id' => 36, 'nombre' => 'CM. BARBACOAS'],
            ['municipio_id' => 36, 'nombre' => 'PQ. SAN FRANCISCO DE CARA'],
            ['municipio_id' => 36, 'nombre' => 'PQ. TAGUAY'],
            ['municipio_id' => 36, 'nombre' => 'PQ. LAS PEÑITAS'],
            ['municipio_id' => 37, 'nombre' => 'CM. VILLA DE CURA'],
            ['municipio_id' => 37, 'nombre' => 'PQ. MAGDALENO'],
            ['municipio_id' => 37, 'nombre' => 'PQ. SAN FRANCISCO DE ASIS'],
            ['municipio_id' => 37, 'nombre' => 'PQ. VALLES DE TUCUTUNEMO'],
            ['municipio_id' => 37, 'nombre' => 'PQ. PQ AUGUSTO MIJARES'],
            ['municipio_id' => 38, 'nombre' => 'CM. PALO NEGRO'],
            ['municipio_id' => 38, 'nombre' => 'PQ. SAN MARTIN DE PORRES'],
            ['municipio_id' => 39, 'nombre' => 'CM. SANTA CRUZ'],
            ['municipio_id' => 40, 'nombre' => 'CM. SAN MATEO'],
            ['municipio_id' => 41, 'nombre' => 'CM. LAS TEJERIAS'],
            ['municipio_id' => 41, 'nombre' => 'PQ. TIARA'],
            ['municipio_id' => 42, 'nombre' => 'CM. EL LIMON'],
            ['municipio_id' => 42, 'nombre' => 'PQ. CA A DE AZUCAR'],
            ['municipio_id' => 43, 'nombre' => 'CM. COLONIA TOVAR'],
            ['municipio_id' => 44, 'nombre' => 'CM. CAMATAGUA'],
            ['municipio_id' => 44, 'nombre' => 'PQ. CARMEN DE CURA'],
            ['municipio_id' => 45, 'nombre' => 'CM. EL CONSEJO'],
            ['municipio_id' => 46, 'nombre' => 'CM. SANTA RITA'],
            ['municipio_id' => 46, 'nombre' => 'PQ. FRANCISCO DE MIRANDA'],
            ['municipio_id' => 46, 'nombre' => 'PQ. MONS FELICIANO G'],
            ['municipio_id' => 47, 'nombre' => 'PQ. OCUMARE DE LA COSTA'],
            ['municipio_id' => 48, 'nombre' => 'PQ. ARISMENDI'],
            ['municipio_id' => 48, 'nombre' => 'PQ. GUADARRAMA'],
            ['municipio_id' => 48, 'nombre' => 'PQ. LA UNION'],
            ['municipio_id' => 48, 'nombre' => 'PQ. SAN ANTONIO'],
            ['municipio_id' => 49, 'nombre' => 'PQ. ALFREDO A LARRIVA'],
            ['municipio_id' => 49, 'nombre' => 'PQ. BARINAS'],
            ['municipio_id' => 49, 'nombre' => 'PQ. SAN SILVESTRE'],
            ['municipio_id' => 49, 'nombre' => 'PQ. SANTA INES'],
            ['municipio_id' => 49, 'nombre' => 'PQ. SANTA LUCIA'],
            ['municipio_id' => 49, 'nombre' => 'PQ. TORUNOS'],
            ['municipio_id' => 49, 'nombre' => 'PQ. EL CARMEN'],
            ['municipio_id' => 49, 'nombre' => 'PQ. ROMULO BETANCOURT'],
            ['municipio_id' => 49, 'nombre' => 'PQ. CORAZON DE JESUS'],
            ['municipio_id' => 49, 'nombre' => 'PQ. RAMON I MENDEZ'],
            ['municipio_id' => 49, 'nombre' => 'PQ. ALTO BARINAS'],
            ['municipio_id' => 49, 'nombre' => 'PQ. MANUEL P FAJARDO'],
            ['municipio_id' => 49, 'nombre' => 'PQ. JUAN A RODRIGUEZ D'],
            ['municipio_id' => 49, 'nombre' => 'PQ. DOMINGA ORTIZ P'],
            ['municipio_id' => 50, 'nombre' => 'PQ. ALTAMIRA'],
            ['municipio_id' => 50, 'nombre' => 'PQ. BARINITAS'],
            ['municipio_id' => 50, 'nombre' => 'PQ. CALDERAS'],
            ['municipio_id' => 51, 'nombre' => 'PQ. SANTA BARBARA'],
            ['municipio_id' => 51, 'nombre' => 'PQ. JOSE IGNACIO DEL PUMAR'],
            ['municipio_id' => 51, 'nombre' => 'PQ. RAMON IGNACIO MENDEZ'],
            ['municipio_id' => 51, 'nombre' => 'PQ. PEDRO BRICEÑO MENDEZ'],
            ['municipio_id' => 52, 'nombre' => 'PQ. EL REAL'],
            ['municipio_id' => 52, 'nombre' => 'PQ. LA LUZ'],
            ['municipio_id' => 52, 'nombre' => 'PQ. OBISPOS'],
            ['municipio_id' => 52, 'nombre' => 'PQ. LOS GUASIMITOS'],
            ['municipio_id' => 53, 'nombre' => 'PQ. CIUDAD BOLIVIA'],
            ['municipio_id' => 53, 'nombre' => 'PQ. IGNACIO BRICEÑO'],
            ['municipio_id' => 53, 'nombre' => 'PQ. PAEZ'],
            ['municipio_id' => 53, 'nombre' => 'PQ. JOSE FELIX RIBAS'],
            ['municipio_id' => 54, 'nombre' => 'PQ. DOLORES'],
            ['municipio_id' => 54, 'nombre' => 'PQ. LIBERTAD'],
            ['municipio_id' => 54, 'nombre' => 'PQ. PALACIO FAJARDO'],
            ['municipio_id' => 54, 'nombre' => 'PQ. SANTA ROSA'],
            ['municipio_id' => 55, 'nombre' => 'PQ. CIUDAD DE NUTRIAS'],
            ['municipio_id' => 55, 'nombre' => 'PQ. EL REGALO'],
            ['municipio_id' => 55, 'nombre' => 'PQ. PUERTO DE NUTRIAS'],
            ['municipio_id' => 55, 'nombre' => 'PQ. SANTA CATALINA'],
            ['municipio_id' => 56, 'nombre' => 'PQ. RODRIGUEZ DOMINGUEZ'],
            ['municipio_id' => 56, 'nombre' => 'PQ. SABANETA'],
            ['municipio_id' => 57, 'nombre' => 'PQ. TICOPORO'],
            ['municipio_id' => 57, 'nombre' => 'PQ. NICOLAS PULIDO'],
            ['municipio_id' => 57, 'nombre' => 'PQ. ANDRES BELLO'],
            ['municipio_id' => 58, 'nombre' => 'PQ. BARRANCAS'],
            ['municipio_id' => 58, 'nombre' => 'PQ. EL SOCORRO'],
            ['municipio_id' => 58, 'nombre' => 'PQ. MASPARRITO'],
            ['municipio_id' => 59, 'nombre' => 'PQ. EL CANTON'],
            ['municipio_id' => 59, 'nombre' => 'PQ. SANTA CRUZ DE GUACAS'],
            ['municipio_id' => 59, 'nombre' => 'PQ. PUERTO VIVAS'],
            ['municipio_id' => 60, 'nombre' => 'PQ. SIMON BOLIVAR'],
            ['municipio_id' => 60, 'nombre' => 'PQ. ONCE DE ABRIL'],
            ['municipio_id' => 60, 'nombre' => 'PQ. VISTA AL SOL'],
            ['municipio_id' => 60, 'nombre' => 'PQ. CHIRICA'],
            ['municipio_id' => 60, 'nombre' => 'PQ. DALLA COSTA'],
            ['municipio_id' => 60, 'nombre' => 'PQ. CACHAMAY'],
            ['municipio_id' => 60, 'nombre' => 'PQ. UNIVERSIDAD'],
            ['municipio_id' => 60, 'nombre' => 'PQ. UNARE'],
            ['municipio_id' => 60, 'nombre' => 'PQ. YOCOIMA'],
            ['municipio_id' => 60, 'nombre' => 'PQ. POZO VERDE'],
            ['municipio_id' => 61, 'nombre' => 'CM. CAICARA DEL ORINOCO'],
            ['municipio_id' => 61, 'nombre' => 'PQ. ASCENSION FARRERAS'],
            ['municipio_id' => 61, 'nombre' => 'PQ. ALTAGRACIA'],
            ['municipio_id' => 61, 'nombre' => 'PQ. LA URBANA'],
            ['municipio_id' => 61, 'nombre' => 'PQ. GUANIAMO'],
            ['municipio_id' => 61, 'nombre' => 'PQ. PIJIGUAOS'],
            ['municipio_id' => 62, 'nombre' => 'PQ. CATEDRAL'],
            ['municipio_id' => 62, 'nombre' => 'PQ. AGUA SALADA'],
            ['municipio_id' => 62, 'nombre' => 'PQ. LA SABANITA'],
            ['municipio_id' => 62, 'nombre' => 'PQ. VISTA HERMOSA'],
            ['municipio_id' => 62, 'nombre' => 'PQ. MARHUANTA'],
            ['municipio_id' => 62, 'nombre' => 'PQ. JOSE ANTONIO PAEZ'],
            ['municipio_id' => 62, 'nombre' => 'PQ. ORINOCO'],
            ['municipio_id' => 62, 'nombre' => 'PQ. PANAPANA'],
            ['municipio_id' => 62, 'nombre' => 'PQ. ZEA'],
            ['municipio_id' => 63, 'nombre' => 'CM. UPATA'],
            ['municipio_id' => 63, 'nombre' => 'PQ. ANDRES ELOY BLANCO'],
            ['municipio_id' => 63, 'nombre' => 'PQ. PEDRO COVA'],
            ['municipio_id' => 64, 'nombre' => 'CM. GUASIPATI'],
            ['municipio_id' => 64, 'nombre' => 'PQ. SALOM'],
            ['municipio_id' => 65, 'nombre' => 'CM. MARIPA'],
            ['municipio_id' => 65, 'nombre' => 'PQ. ARIPAO'],
            ['municipio_id' => 65, 'nombre' => 'PQ. LAS MAJADAS'],
            ['municipio_id' => 65, 'nombre' => 'PQ. MOITACO'],
            ['municipio_id' => 65, 'nombre' => 'PQ. GUARATARO'],
            ['municipio_id' => 66, 'nombre' => 'CM. TUMEREMO'],
            ['municipio_id' => 66, 'nombre' => 'PQ. DALLA COSTA'],
            ['municipio_id' => 66, 'nombre' => 'PQ. SAN ISIDRO'],
            ['municipio_id' => 67, 'nombre' => 'CM. CIUDAD PIAR'],
            ['municipio_id' => 67, 'nombre' => 'PQ. SAN FRANCISCO'],
            ['municipio_id' => 67, 'nombre' => 'PQ. BARCELONETA'],
            ['municipio_id' => 67, 'nombre' => 'PQ. SANTA BARBARA'],
            ['municipio_id' => 68, 'nombre' => 'CM. SANTA ELENA DE UAIREN'],
            ['municipio_id' => 68, 'nombre' => 'PQ. IKABARU'],
            ['municipio_id' => 69, 'nombre' => 'CM. EL CALLAO'],
            ['municipio_id' => 70, 'nombre' => 'CM. EL PALMAR'],
            ['municipio_id' => 71, 'nombre' => 'PQ. BEJUMA'],
            ['municipio_id' => 71, 'nombre' => 'PQ. CANOABO'],
            ['municipio_id' => 71, 'nombre' => 'PQ. SIMON BOLIVAR'],
            ['municipio_id' => 72, 'nombre' => 'PQ. GUIGUE'],
            ['municipio_id' => 72, 'nombre' => 'PQ. BELEN'],
            ['municipio_id' => 72, 'nombre' => 'PQ. TACARIGUA'],
            ['municipio_id' => 73, 'nombre' => 'PQ. MARIARA'],
            ['municipio_id' => 73, 'nombre' => 'PQ. AGUAS CALIENTES'],
            ['municipio_id' => 74, 'nombre' => 'PQ. GUACARA'],
            ['municipio_id' => 74, 'nombre' => 'PQ. CIUDAD ALIANZA'],
            ['municipio_id' => 74, 'nombre' => 'PQ. YAGUA'],
            ['municipio_id' => 75, 'nombre' => 'PQ. MONTALBAN'],
            ['municipio_id' => 76, 'nombre' => 'PQ. MORON'],
            ['municipio_id' => 76, 'nombre' => 'PQ. URAMA'],
            ['municipio_id' => 77, 'nombre' => 'PQ. DEMOCRACIA'],
            ['municipio_id' => 77, 'nombre' => 'PQ. FRATERNIDAD'],
            ['municipio_id' => 77, 'nombre' => 'PQ. GOAIGOAZA'],
            ['municipio_id' => 77, 'nombre' => 'PQ. JUAN JOSE FLORES'],
            ['municipio_id' => 77, 'nombre' => 'PQ. BARTOLOME SALOM'],
            ['municipio_id' => 77, 'nombre' => 'PQ. UNION'],
            ['municipio_id' => 77, 'nombre' => 'PQ. BORBURATA'],
            ['municipio_id' => 77, 'nombre' => 'PQ. PATANEMO'],
            ['municipio_id' => 78, 'nombre' => 'PQ. SAN JOAQUIN'],
            ['municipio_id' => 79, 'nombre' => 'PQ. CANDELARIA'],
            ['municipio_id' => 79, 'nombre' => 'PQ. CATEDRAL'],
            ['municipio_id' => 79, 'nombre' => 'PQ. EL SOCORRO'],
            ['municipio_id' => 79, 'nombre' => 'PQ. MIGUEL PEÑA'],
            ['municipio_id' => 79, 'nombre' => 'PQ. SAN BLAS'],
            ['municipio_id' => 79, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 79, 'nombre' => 'PQ. SANTA ROSA'],
            ['municipio_id' => 79, 'nombre' => 'PQ. RAFAEL URDANETA'],
            ['municipio_id' => 79, 'nombre' => 'PQ. NEGRO PRIMERO'],
            ['municipio_id' => 80, 'nombre' => 'PQ. MIRANDA'],
            ['municipio_id' => 81, 'nombre' => 'PQ. U LOS GUAYOS'],
            ['municipio_id' => 82, 'nombre' => 'PQ. NAGUANAGUA'],
            ['municipio_id' => 83, 'nombre' => 'PQ. URB SAN DIEGO'],
            ['municipio_id' => 84, 'nombre' => 'PQ. U TOCUYITO'],
            ['municipio_id' => 84, 'nombre' => 'PQ. U INDEPENDENCIA'],
            ['municipio_id' => 85, 'nombre' => 'PQ. COJEDES'],
            ['municipio_id' => 85, 'nombre' => 'PQ. JUAN DE MATA SUAREZ'],
            ['municipio_id' => 86, 'nombre' => 'PQ. TINAQUILLO'],
            ['municipio_id' => 87, 'nombre' => 'PQ. EL BAUL'],
            ['municipio_id' => 87, 'nombre' => 'PQ. SUCRE'],
            ['municipio_id' => 88, 'nombre' => 'PQ. EL PAO'],
            ['municipio_id' => 89, 'nombre' => 'PQ. LIBERTAD DE COJEDES'],
            ['municipio_id' => 89, 'nombre' => 'PQ. EL AMPARO'],
            ['municipio_id' => 90, 'nombre' => 'PQ. SAN CARLOS DE AUSTRIA'],
            ['municipio_id' => 90, 'nombre' => 'PQ. JUAN ANGEL BRAVO'],
            ['municipio_id' => 90, 'nombre' => 'PQ. MANUEL MANRIQUE'],
            ['municipio_id' => 91, 'nombre' => 'PQ. GRL/JEFE JOSE L SILVA'],
            ['municipio_id' => 92, 'nombre' => 'PQ. MACAPO'],
            ['municipio_id' => 92, 'nombre' => 'PQ. LA AGUADITA'],
            ['municipio_id' => 93, 'nombre' => 'PQ. ROMULO GALLEGOS'],
            ['municipio_id' => 94, 'nombre' => 'PQ. SAN JUAN DE LOS CAYOS'],
            ['municipio_id' => 94, 'nombre' => 'PQ. CAPADARE'],
            ['municipio_id' => 94, 'nombre' => 'PQ. LA PASTORA'],
            ['municipio_id' => 94, 'nombre' => 'PQ. LIBERTADOR'],
            ['municipio_id' => 95, 'nombre' => 'PQ. SAN LUIS'],
            ['municipio_id' => 95, 'nombre' => 'PQ. ARACUA'],
            ['municipio_id' => 95, 'nombre' => 'PQ. LA PEÑA'],
            ['municipio_id' => 96, 'nombre' => 'PQ. CAPATARIDA'],
            ['municipio_id' => 96, 'nombre' => 'PQ. BOROJO'],
            ['municipio_id' => 96, 'nombre' => 'PQ. SEQUE'],
            ['municipio_id' => 96, 'nombre' => 'PQ. ZAZARIDA'],
            ['municipio_id' => 96, 'nombre' => 'PQ. BARIRO'],
            ['municipio_id' => 96, 'nombre' => 'PQ. GUAJIRO'],
            ['municipio_id' => 97, 'nombre' => 'PQ. NORTE'],
            ['municipio_id' => 97, 'nombre' => 'PQ. CARIRUBANA'],
            ['municipio_id' => 97, 'nombre' => 'PQ. PUNTA CARDON'],
            ['municipio_id' => 97, 'nombre' => 'PQ. SANTA ANA'],
            ['municipio_id' => 98, 'nombre' => 'PQ. LA VELA DE CORO'],
            ['municipio_id' => 98, 'nombre' => 'PQ. ACURIGUA'],
            ['municipio_id' => 98, 'nombre' => 'PQ. GUAIBACOA'],
            ['municipio_id' => 98, 'nombre' => 'PQ. MACORUCA'],
            ['municipio_id' => 98, 'nombre' => 'PQ. LAS CALDERAS'],
            ['municipio_id' => 99, 'nombre' => 'PQ. PEDREGAL'],
            ['municipio_id' => 99, 'nombre' => 'PQ. AGUA CLARA'],
            ['municipio_id' => 99, 'nombre' => 'PQ. AVARIA'],
            ['municipio_id' => 99, 'nombre' => 'PQ. PIEDRA GRANDE'],
            ['municipio_id' => 99, 'nombre' => 'PQ. PURURECHE'],
            ['municipio_id' => 100, 'nombre' => 'PQ. PUEBLO NUEVO'],
            ['municipio_id' => 100, 'nombre' => 'PQ. ADICORA'],
            ['municipio_id' => 100, 'nombre' => 'PQ. BARAIVED'],
            ['municipio_id' => 100, 'nombre' => 'PQ. BUENA VISTA'],
            ['municipio_id' => 100, 'nombre' => 'PQ. JADACAQUIVA'],
            ['municipio_id' => 100, 'nombre' => 'PQ. MORUY'],
            ['municipio_id' => 100, 'nombre' => 'PQ. EL VINCULO'],
            ['municipio_id' => 100, 'nombre' => 'PQ. EL HATO'],
            ['municipio_id' => 100, 'nombre' => 'PQ. ADAURE'],
            ['municipio_id' => 101, 'nombre' => 'PQ. CHURUGUARA'],
            ['municipio_id' => 101, 'nombre' => 'PQ. AGUA LARGA'],
            ['municipio_id' => 101, 'nombre' => 'PQ. INDEPENDENCIA'],
            ['municipio_id' => 101, 'nombre' => 'PQ. MAPARARI'],
            ['municipio_id' => 101, 'nombre' => 'PQ. EL PAUJI'],
            ['municipio_id' => 102, 'nombre' => 'PQ. MENE DE MAUROA'],
            ['municipio_id' => 102, 'nombre' => 'PQ. CASIGUA'],
            ['municipio_id' => 102, 'nombre' => 'PQ. SAN FELIX'],
            ['municipio_id' => 103, 'nombre' => 'PQ. SAN ANTONIO'],
            ['municipio_id' => 103, 'nombre' => 'PQ. SAN GABRIEL'],
            ['municipio_id' => 103, 'nombre' => 'PQ. SANTA ANA'],
            ['municipio_id' => 103, 'nombre' => 'PQ. GUZMAN GUILLERMO'],
            ['municipio_id' => 103, 'nombre' => 'PQ. MITARE'],
            ['municipio_id' => 103, 'nombre' => 'PQ. SABANETA'],
            ['municipio_id' => 103, 'nombre' => 'PQ. RIO SECO'],
            ['municipio_id' => 104, 'nombre' => 'PQ. CABURE'],
            ['municipio_id' => 104, 'nombre' => 'PQ. CURIMAGUA'],
            ['municipio_id' => 104, 'nombre' => 'PQ. COLINA'],
            ['municipio_id' => 105, 'nombre' => 'PQ. TUCACAS'],
            ['municipio_id' => 105, 'nombre' => 'PQ. BOCA DE AROA'],
            ['municipio_id' => 106, 'nombre' => 'PQ. PUERTO CUMAREBO'],
            ['municipio_id' => 106, 'nombre' => 'PQ. LA CIENAGA'],
            ['municipio_id' => 106, 'nombre' => 'PQ. LA SOLEDAD'],
            ['municipio_id' => 106, 'nombre' => 'PQ. PUEBLO CUMAREBO'],
            ['municipio_id' => 106, 'nombre' => 'PQ. ZAZARIDA'],
            ['municipio_id' => 107, 'nombre' => 'CM. DABAJURO'],
            ['municipio_id' => 108, 'nombre' => 'PQ. CHICHIRIVICHE'],
            ['municipio_id' => 108, 'nombre' => 'PQ. BOCA DE TOCUYO'],
            ['municipio_id' => 108, 'nombre' => 'PQ. TOCUYO DE LA COSTA'],
            ['municipio_id' => 109, 'nombre' => 'PQ. LOS TAQUES'],
            ['municipio_id' => 109, 'nombre' => 'PQ. JUDIBANA'],
            ['municipio_id' => 110, 'nombre' => 'PQ. PIRITU'],
            ['municipio_id' => 110, 'nombre' => 'PQ. SAN JOSE DE LA COSTA'],
            ['municipio_id' => 111, 'nombre' => 'PQ. STA.CRUZ DE BUCARAL'],
            ['municipio_id' => 111, 'nombre' => 'PQ. EL CHARAL'],
            ['municipio_id' => 111, 'nombre' => 'PQ. LAS VEGAS DEL TUY'],
            ['municipio_id' => 112, 'nombre' => 'CM. MIRIMIRE'],
            ['municipio_id' => 113, 'nombre' => 'PQ. JACURA'],
            ['municipio_id' => 113, 'nombre' => 'PQ. AGUA LINDA'],
            ['municipio_id' => 113, 'nombre' => 'PQ. ARAURIMA'],
            ['municipio_id' => 114, 'nombre' => 'CM. YARACAL'],
            ['municipio_id' => 115, 'nombre' => 'CM. PALMA SOLA'],
            ['municipio_id' => 116, 'nombre' => 'PQ. SUCRE'],
            ['municipio_id' => 116, 'nombre' => 'PQ. PECAYA'],
            ['municipio_id' => 117, 'nombre' => 'PQ. URUMACO'],
            ['municipio_id' => 117, 'nombre' => 'PQ. BRUZUAL'],
            ['municipio_id' => 118, 'nombre' => 'CM. TOCOPERO'],
            ['municipio_id' => 119, 'nombre' => 'PQ. VALLE DE LA PASCUA'],
            ['municipio_id' => 119, 'nombre' => 'PQ. ESPINO'],
            ['municipio_id' => 120, 'nombre' => 'PQ. EL SOMBRERO'],
            ['municipio_id' => 120, 'nombre' => 'PQ. SOSA'],
            ['municipio_id' => 121, 'nombre' => 'PQ. CALABOZO'],
            ['municipio_id' => 121, 'nombre' => 'PQ. EL CALVARIO'],
            ['municipio_id' => 121, 'nombre' => 'PQ. EL RASTRO'],
            ['municipio_id' => 121, 'nombre' => 'PQ. GUARDATINAJAS'],
            ['municipio_id' => 122, 'nombre' => 'PQ. ALTAGRACIA DE ORITUCO'],
            ['municipio_id' => 122, 'nombre' => 'PQ. LEZAMA'],
            ['municipio_id' => 122, 'nombre' => 'PQ. LIBERTAD DE ORITUCO'],
            ['municipio_id' => 122, 'nombre' => 'PQ. SAN FCO DE MACAIRA'],
            ['municipio_id' => 122, 'nombre' => 'PQ. SAN RAFAEL DE ORITUCO'],
            ['municipio_id' => 122, 'nombre' => 'PQ. SOUBLETTE'],
            ['municipio_id' => 122, 'nombre' => 'PQ. PASO REAL DE MACAIRA'],
            ['municipio_id' => 123, 'nombre' => 'PQ. TUCUPIDO'],
            ['municipio_id' => 123, 'nombre' => 'PQ. SAN RAFAEL DE LAYA'],
            ['municipio_id' => 124, 'nombre' => 'PQ.SAN JUAN DE LOS MORROS'],
            ['municipio_id' => 124, 'nombre' => 'PQ. PARAPARA'],
            ['municipio_id' => 124, 'nombre' => 'PQ. CANTAGALLO'],
            ['municipio_id' => 125, 'nombre' => 'PQ. ZARAZA'],
            ['municipio_id' => 125, 'nombre' => 'PQ. SAN JOSE DE UNARE'],
            ['municipio_id' => 126, 'nombre' => 'PQ. CAMAGUAN'],
            ['municipio_id' => 126, 'nombre' => 'PQ. PUERTO MIRANDA'],
            ['municipio_id' => 126, 'nombre' => 'PQ. UVERITO'],
            ['municipio_id' => 127, 'nombre' => 'PQ. SAN JOSE DE GUARIBE'],
            ['municipio_id' => 128, 'nombre' => 'PQ. LAS MERCEDES'],
            ['municipio_id' => 128, 'nombre' => 'PQ. STA RITA DE MANAPIRE'],
            ['municipio_id' => 128, 'nombre' => 'PQ. CABRUTA'],
            ['municipio_id' => 129, 'nombre' => 'PQ. EL SOCORRO'],
            ['municipio_id' => 130, 'nombre' => 'PQ. ORTIZ'],
            ['municipio_id' => 130, 'nombre' => 'PQ. SAN FCO. DE TIZNADOS'],
            ['municipio_id' => 130, 'nombre' => 'PQ. SAN JOSE DE TIZNADOS'],
            ['municipio_id' => 130, 'nombre' => 'PQ. S LORENZO DE TIZNADOS'],
            ['municipio_id' => 131, 'nombre' => 'PQ. SANTA MARIA DE IPIRE'],
            ['municipio_id' => 131, 'nombre' => 'PQ. ALTAMIRA'],
            ['municipio_id' => 132, 'nombre' => 'PQ. CHAGUARAMAS'],
            ['municipio_id' => 133, 'nombre' => 'PQ. GUAYABAL'],
            ['municipio_id' => 133, 'nombre' => 'PQ. CAZORLA'],
            ['municipio_id' => 134, 'nombre' => 'PQ. FREITEZ'],
            ['municipio_id' => 134, 'nombre' => 'PQ. JOSE MARIA BLANCO'],
            ['municipio_id' => 135, 'nombre' => 'PQ. CATEDRAL'],
            ['municipio_id' => 135, 'nombre' => 'PQ. LA CONCEPCION'],
            ['municipio_id' => 135, 'nombre' => 'PQ. SANTA ROSA'],
            ['municipio_id' => 135, 'nombre' => 'PQ. UNION'],
            ['municipio_id' => 135, 'nombre' => 'PQ. EL CUJI'],
            ['municipio_id' => 135, 'nombre' => 'PQ. TAMACA'],
            ['municipio_id' => 135, 'nombre' => 'PQ. JUAN DE VILLEGAS'],
            ['municipio_id' => 135, 'nombre' => 'PQ. AGUEDO F. ALVARADO'],
            ['municipio_id' => 135, 'nombre' => 'PQ. BUENA VISTA'],
            ['municipio_id' => 135, 'nombre' => 'PQ. JUAREZ'],
            ['municipio_id' => 136, 'nombre' => 'PQ. JUAN B RODRIGUEZ'],
            ['municipio_id' => 136, 'nombre' => 'PQ. DIEGO DE LOZADA'],
            ['municipio_id' => 136, 'nombre' => 'PQ. SAN MIGUEL'],
            ['municipio_id' => 136, 'nombre' => 'PQ. CUARA'],
            ['municipio_id' => 136, 'nombre' => 'PQ. PARAISO DE SAN JOSE'],
            ['municipio_id' => 136, 'nombre' => 'PQ. TINTORERO'],
            ['municipio_id' => 136, 'nombre' => 'PQ. JOSE BERNARDO DORANTE'],
            ['municipio_id' => 136, 'nombre' => 'PQ. CRNEL. MARIANO PERAZA'],
            ['municipio_id' => 137, 'nombre' => 'PQ. BOLIVAR'],
            ['municipio_id' => 137, 'nombre' => 'PQ. ANZOATEGUI'],
            ['municipio_id' => 137, 'nombre' => 'PQ. GUARICO'],
            ['municipio_id' => 137, 'nombre' => 'PQ. HUMOCARO ALTO'],
            ['municipio_id' => 137, 'nombre' => 'PQ. HUMOCARO BAJO'],
            ['municipio_id' => 137, 'nombre' => 'PQ. MORAN'],
            ['municipio_id' => 137, 'nombre' => 'PQ. HILARIO LUNA Y LUNA'],
            ['municipio_id' => 137, 'nombre' => 'PQ. LA CANDELARIA'],
            ['municipio_id' => 138, 'nombre' => 'PQ. CABUDARE'],
            ['municipio_id' => 138, 'nombre' => 'PQ. JOSE G. BASTIDAS'],
            ['municipio_id' => 138, 'nombre' => 'PQ. AGUA VIVA'],
            ['municipio_id' => 139, 'nombre' => 'PQ. TRINIDAD SAMUEL'],
            ['municipio_id' => 139, 'nombre' => 'PQ. ANTONIO DIAZ'],
            ['municipio_id' => 139, 'nombre' => 'PQ. CAMACARO'],
            ['municipio_id' => 139, 'nombre' => 'PQ. CASTAÑEDA'],
            ['municipio_id' => 139, 'nombre' => 'PQ. CHIQUINQUIRA'],
            ['municipio_id' => 139, 'nombre' => 'PQ. ESPINOZA LOS MONTEROS'],
            ['municipio_id' => 139, 'nombre' => 'PQ. LARA'],
            ['municipio_id' => 139, 'nombre' => 'PQ. MANUEL MORILLO'],
            ['municipio_id' => 139, 'nombre' => 'PQ. MONTES DE OCA'],
            ['municipio_id' => 139, 'nombre' => 'PQ. TORRES'],
            ['municipio_id' => 139, 'nombre' => 'PQ. EL BLANCO'],
            ['municipio_id' => 139, 'nombre' => 'PQ. MONTA A VERDE'],
            ['municipio_id' => 139, 'nombre' => 'PQ. HERIBERTO ARROYO'],
            ['municipio_id' => 139, 'nombre' => 'PQ. LAS MERCEDES'],
            ['municipio_id' => 139, 'nombre' => 'PQ. CECILIO ZUBILLAGA'],
            ['municipio_id' => 139, 'nombre' => 'PQ. REYES VARGAS'],
            ['municipio_id' => 139, 'nombre' => 'PQ. ALTAGRACIA'],
            ['municipio_id' => 140, 'nombre' => 'PQ. SIQUISIQUE'],
            ['municipio_id' => 140, 'nombre' => 'PQ. SAN MIGUEL'],
            ['municipio_id' => 140, 'nombre' => 'PQ. XAGUAS'],
            ['municipio_id' => 140, 'nombre' => 'PQ. MOROTURO'],
            ['municipio_id' => 141, 'nombre' => 'PQ. PIO TAMAYO'],
            ['municipio_id' => 141, 'nombre' => 'PQ. YACAMBU'],
            ['municipio_id' => 141, 'nombre' => 'PQ. QBDA. HONDA DE GUACHE'],
            ['municipio_id' => 142, 'nombre' => 'PQ. SARARE'],
            ['municipio_id' => 142, 'nombre' => 'PQ. GUSTAVO VEGAS LEON'],
            ['municipio_id' => 142, 'nombre' => 'PQ. BURIA'],
            ['municipio_id' => 143, 'nombre' => 'PQ. GABRIEL PICON G.'],
            ['municipio_id' => 143, 'nombre' => 'PQ. HECTOR AMABLE MORA'],
            ['municipio_id' => 143, 'nombre' => 'PQ. JOSE NUCETE SARDI'],
            ['municipio_id' => 143, 'nombre' => 'PQ. PULIDO MENDEZ'],
            ['municipio_id' => 143, 'nombre' => 'PQ. PTE. ROMULO GALLEGOS'],
            ['municipio_id' => 143, 'nombre' => 'PQ. PRESIDENTE BETANCOURT'],
            ['municipio_id' => 143, 'nombre' => 'PQ. PRESIDENTE PAEZ'],
            ['municipio_id' => 144, 'nombre' => 'CM. LA AZULITA'],
            ['municipio_id' => 145, 'nombre' => 'CM. CANAGUA'],
            ['municipio_id' => 145, 'nombre' => 'PQ. CAPURI'],
            ['municipio_id' => 145, 'nombre' => 'PQ. CHACANTA'],
            ['municipio_id' => 145, 'nombre' => 'PQ. EL MOLINO'],
            ['municipio_id' => 145, 'nombre' => 'PQ. GUAIMARAL'],
            ['municipio_id' => 145, 'nombre' => 'PQ. MUCUTUY'],
            ['municipio_id' => 145, 'nombre' => 'PQ. MUCUCHACHI'],
            ['municipio_id' => 146, 'nombre' => 'PQ. ACEQUIAS'],
            ['municipio_id' => 146, 'nombre' => 'PQ. JAJI'],
            ['municipio_id' => 146, 'nombre' => 'PQ. LA MESA'],
            ['municipio_id' => 146, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 146, 'nombre' => 'PQ. MONTALBAN'],
            ['municipio_id' => 146, 'nombre' => 'PQ. MATRIZ'],
            ['municipio_id' => 146, 'nombre' => 'PQ. FERNANDEZ PEÑA'],
            ['municipio_id' => 147, 'nombre' => 'CM. GUARAQUE'],
            ['municipio_id' => 147, 'nombre' => 'PQ. MESA DE QUINTERO'],
            ['municipio_id' => 147, 'nombre' => 'PQ. RIO NEGRO'],
            ['municipio_id' => 148, 'nombre' => 'CM. ARAPUEY'],
            ['municipio_id' => 148, 'nombre' => 'PQ. PALMIRA'],
            ['municipio_id' => 149, 'nombre' => 'CM. TORONDOY'],
            ['municipio_id' => 149, 'nombre' => 'PQ. SAN CRISTOBAL DE T'],
            ['municipio_id' => 150, 'nombre' => 'PQ. ARIAS'],
            ['municipio_id' => 150, 'nombre' => 'PQ. SAGRARIO'],
            ['municipio_id' => 150, 'nombre' => 'PQ. MILLA'],
            ['municipio_id' => 150, 'nombre' => 'PQ. EL LLANO'],
            ['municipio_id' => 150, 'nombre' => 'PQ. JUAN RODRIGUEZ SUAREZ'],
            ['municipio_id' => 150, 'nombre' => 'PQ. JACINTO PLAZA'],
            ['municipio_id' => 150, 'nombre' => 'PQ. DOMINGO PEÑA'],
            ['municipio_id' => 150, 'nombre' => 'PQ. GONZALO PICON FEBRES'],
            ['municipio_id' => 150, 'nombre' => 'PQ. OSUNA RODRIGUEZ'],
            ['municipio_id' => 150, 'nombre' => 'PQ. LASSO DE LA VEGA'],
            ['municipio_id' => 150, 'nombre' => 'PQ. CARACCIOLO PARRA P'],
            ['municipio_id' => 150, 'nombre' => 'PQ. MARIANO PICON SALAS'],
            ['municipio_id' => 150, 'nombre' => 'PQ. ANTONIO SPINETTI DINI'],
            ['municipio_id' => 150, 'nombre' => 'PQ. EL MORRO'],
            ['municipio_id' => 150, 'nombre' => 'PQ. LOS NEVADOS'],
            ['municipio_id' => 151, 'nombre' => 'CM. TABAY'],
            ['municipio_id' => 152, 'nombre' => 'CM. CHACHOPO'],
            ['municipio_id' => 152, 'nombre' => 'PQ. ANDRES ELOY BLANCO'],
            ['municipio_id' => 152, 'nombre' => 'PQ. PIÑANGO'],
            ['municipio_id' => 152, 'nombre' => 'PQ. LA VENTA'],
            ['municipio_id' => 153, 'nombre' => 'CM. STA CRUZ DE MORA'],
            ['municipio_id' => 153, 'nombre' => 'PQ. MESA BOLIVAR'],
            ['municipio_id' => 153, 'nombre' => 'PQ. MESA DE LAS PALMAS'],
            ['municipio_id' => 154, 'nombre' => 'CM. STA ELENA DE ARENALES'],
            ['municipio_id' => 154, 'nombre' => 'PQ. ELOY PAREDES'],
            ['municipio_id' => 154, 'nombre' => 'PQ. PQ R DE ALCAZAR'],
            ['municipio_id' => 155, 'nombre' => 'CM. TUCANI'],
            ['municipio_id' => 155, 'nombre' => 'PQ. FLORENCIO RAMIREZ'],
            ['municipio_id' => 156, 'nombre' => 'CM. SANTO DOMINGO'],
            ['municipio_id' => 156, 'nombre' => 'PQ. LAS PIEDRAS'],
            ['municipio_id' => 157, 'nombre' => 'CM. PUEBLO LLANO'],
            ['municipio_id' => 158, 'nombre' => 'CM. MUCUCHIES'],
            ['municipio_id' => 158, 'nombre' => 'PQ. MUCURUBA'],
            ['municipio_id' => 158, 'nombre' => 'PQ. SAN RAFAEL'],
            ['municipio_id' => 158, 'nombre' => 'PQ. CACUTE'],
            ['municipio_id' => 158, 'nombre' => 'PQ. LA TOMA'],
            ['municipio_id' => 159, 'nombre' => 'CM. BAILADORES'],
            ['municipio_id' => 159, 'nombre' => 'PQ. GERONIMO MALDONADO'],
            ['municipio_id' => 160, 'nombre' => 'CM. LAGUNILLAS'],
            ['municipio_id' => 160, 'nombre' => 'PQ. CHIGUARA'],
            ['municipio_id' => 160, 'nombre' => 'PQ. ESTANQUES'],
            ['municipio_id' => 160, 'nombre' => 'PQ. SAN JUAN'],
            ['municipio_id' => 160, 'nombre' => 'PQ. PUEBLO NUEVO DEL SUR'],
            ['municipio_id' => 160, 'nombre' => 'PQ. LA TRAMPA'],
            ['municipio_id' => 161, 'nombre' => 'PQ. EL LLANO'],
            ['municipio_id' => 161, 'nombre' => 'PQ. TOVAR'],
            ['municipio_id' => 161, 'nombre' => 'PQ. EL AMPARO'],
            ['municipio_id' => 161, 'nombre' => 'PQ. SAN FRANCISCO'],
            ['municipio_id' => 162, 'nombre' => 'CM. NUEVA BOLIVIA'],
            ['municipio_id' => 162, 'nombre' => 'PQ. INDEPENDENCIA'],
            ['municipio_id' => 162, 'nombre' => 'PQ. MARIA C PALACIOS'],
            ['municipio_id' => 162, 'nombre' => 'PQ. SANTA APOLONIA'],
            ['municipio_id' => 163, 'nombre' => 'CM. STA MARIA DE CAPARO'],
            ['municipio_id' => 164, 'nombre' => 'CM. ARICAGUA'],
            ['municipio_id' => 164, 'nombre' => 'PQ. SAN ANTONIO'],
            ['municipio_id' => 165, 'nombre' => 'CM. ZEA'],
            ['municipio_id' => 165, 'nombre' => 'PQ. CAÑO EL TIGRE'],
            ['municipio_id' => 166, 'nombre' => 'PQ. CAUCAGUA'],
            ['municipio_id' => 166, 'nombre' => 'PQ. ARAGUITA'],
            ['municipio_id' => 166, 'nombre' => 'PQ. AREVALO GONZALEZ'],
            ['municipio_id' => 166, 'nombre' => 'PQ. CAPAYA'],
            ['municipio_id' => 166, 'nombre' => 'PQ. PANAQUIRE'],
            ['municipio_id' => 166, 'nombre' => 'PQ. RIBAS'],
            ['municipio_id' => 166, 'nombre' => 'PQ. EL CAFE'],
            ['municipio_id' => 166, 'nombre' => 'PQ. MARIZAPA'],
            ['municipio_id' => 167, 'nombre' => 'PQ. HIGUEROTE'],
            ['municipio_id' => 167, 'nombre' => 'PQ. CURIEPE'],
            ['municipio_id' => 167, 'nombre' => 'PQ. TACARIGUA'],
            ['municipio_id' => 168, 'nombre' => 'PQ. LOS TEQUES'],
            ['municipio_id' => 168, 'nombre' => 'PQ. CECILIO ACOSTA'],
            ['municipio_id' => 168, 'nombre' => 'PQ. PARACOTOS'],
            ['municipio_id' => 168, 'nombre' => 'PQ. SAN PEDRO'],
            ['municipio_id' => 168, 'nombre' => 'PQ. TACATA'],
            ['municipio_id' => 168, 'nombre' => 'PQ. EL JARILLO'],
            ['municipio_id' => 168, 'nombre' => 'PQ. ALTAGRACIA DE LA M'],
            ['municipio_id' => 169, 'nombre' => 'PQ. STA TERESA DEL TUY'],
            ['municipio_id' => 169, 'nombre' => 'PQ. EL CARTANAL'],
            ['municipio_id' => 170, 'nombre' => 'PQ. OCUMARE DEL TUY'],
            ['municipio_id' => 170, 'nombre' => 'PQ. LA DEMOCRACIA'],
            ['municipio_id' => 170, 'nombre' => 'PQ. SANTA BARBARA'],
            ['municipio_id' => 171, 'nombre' => 'PQ. RIO CHICO'],
            ['municipio_id' => 171, 'nombre' => 'PQ. EL GUAPO'],
            ['municipio_id' => 171, 'nombre' => 'PQ.TACARIGUA DE LA LAGUNA'],
            ['municipio_id' => 171, 'nombre' => 'PQ. PAPARO'],
            ['municipio_id' => 171, 'nombre' => 'PQ. SN FERNANDO DEL GUAPO'],
            ['municipio_id' => 172, 'nombre' => 'PQ. SANTA LUCIA'],
            ['municipio_id' => 173, 'nombre' => 'PQ. GUARENAS'],
            ['municipio_id' => 174, 'nombre' => 'PQ. PETARE'],
            ['municipio_id' => 174, 'nombre' => 'PQ. LEONCIO MARTINEZ'],
            ['municipio_id' => 174, 'nombre' => 'PQ. CAUCAGUITA'],
            ['municipio_id' => 174, 'nombre' => 'PQ. FILAS DE MARICHES'],
            ['municipio_id' => 174, 'nombre' => 'PQ. LA DOLORITA'],
            ['municipio_id' => 175, 'nombre' => 'PQ. CUA'],
            ['municipio_id' => 175, 'nombre' => 'PQ. NUEVA CUA'],
            ['municipio_id' => 176, 'nombre' => 'PQ. GUATIRE'],
            ['municipio_id' => 176, 'nombre' => 'PQ. BOLIVAR'],
            ['municipio_id' => 177, 'nombre' => 'PQ. CHARALLAVE'],
            ['municipio_id' => 177, 'nombre' => 'PQ. LAS BRISAS'],
            ['municipio_id' => 178, 'nombre' => 'PQ. SAN ANTONIO LOS ALTOS'],
            ['municipio_id' => 179, 'nombre' => 'PQ. SAN JOSE DE BARLOVENTO'],
            ['municipio_id' => 179, 'nombre' => 'PQ. CUMBO'],
            ['municipio_id' => 180, 'nombre' => 'PQ. SAN FCO DE YARE'],
            ['municipio_id' => 180, 'nombre' => 'PQ. S ANTONIO DE YARE'],
            ['municipio_id' => 181, 'nombre' => 'PQ. BARUTA'],
            ['municipio_id' => 181, 'nombre' => 'PQ. EL CAFETAL'],
            ['municipio_id' => 181, 'nombre' => 'PQ. LAS MINAS DE BARUTA'],
            ['municipio_id' => 182, 'nombre' => 'PQ. CARRIZAL'],
            ['municipio_id' => 183, 'nombre' => 'PQ. CHACAO'],
            ['municipio_id' => 184, 'nombre' => 'PQ. EL HATILLO'],
            ['municipio_id' => 185, 'nombre' => 'PQ. MAMPORAL'],
            ['municipio_id' => 186, 'nombre' => 'PQ. CUPIRA'],
            ['municipio_id' => 186, 'nombre' => 'PQ. MACHURUCUTO'],
            ['municipio_id' => 187, 'nombre' => 'CM. SAN ANTONIO'],
            ['municipio_id' => 187, 'nombre' => 'PQ. SAN FRANCISCO'],
            ['municipio_id' => 188, 'nombre' => 'CM. CARIPITO'],
            ['municipio_id' => 189, 'nombre' => 'CM. CARIPE'],
            ['municipio_id' => 189, 'nombre' => 'PQ. TERESEN'],
            ['municipio_id' => 189, 'nombre' => 'PQ. EL GUACHARO'],
            ['municipio_id' => 189, 'nombre' => 'PQ. SAN AGUSTIN'],
            ['municipio_id' => 189, 'nombre' => 'PQ. LA GUANOTA'],
            ['municipio_id' => 189, 'nombre' => 'PQ. SABANA DE PIEDRA'],
            ['municipio_id' => 190, 'nombre' => 'CM. CAICARA'],
            ['municipio_id' => 190, 'nombre' => 'PQ. AREO'],
            ['municipio_id' => 190, 'nombre' => 'PQ. SAN FELIX'],
            ['municipio_id' => 190, 'nombre' => 'PQ. VIENTO FRESCO'],
            ['municipio_id' => 191, 'nombre' => 'CM. PUNTA DE MATA'],
            ['municipio_id' => 191, 'nombre' => 'PQ. EL TEJERO'],
            ['municipio_id' => 192, 'nombre' => 'CM. TEMBLADOR'],
            ['municipio_id' => 192, 'nombre' => 'PQ. TABASCA'],
            ['municipio_id' => 192, 'nombre' => 'PQ. LAS ALHUACAS'],
            ['municipio_id' => 192, 'nombre' => 'PQ. CHAGUARAMAS'],
            ['municipio_id' => 193, 'nombre' => 'PQ. EL FURRIAL'],
            ['municipio_id' => 193, 'nombre' => 'PQ. JUSEPIN'],
            ['municipio_id' => 193, 'nombre' => 'PQ. EL COROZO'],
            ['municipio_id' => 193, 'nombre' => 'PQ. SAN VICENTE'],
            ['municipio_id' => 193, 'nombre' => 'PQ. LA PICA'],
            ['municipio_id' => 193, 'nombre' => 'PQ. ALTO DE LOS GODOS'],
            ['municipio_id' => 193, 'nombre' => 'PQ. BOQUERON'],
            ['municipio_id' => 193, 'nombre' => 'PQ. LAS COCUIZAS'],
            ['municipio_id' => 193, 'nombre' => 'PQ. SANTA CRUZ'],
            ['municipio_id' => 193, 'nombre' => 'PQ. SAN SIMON'],
            ['municipio_id' => 194, 'nombre' => 'CM. ARAGUA'],
            ['municipio_id' => 194, 'nombre' => 'PQ. CHAGUARAMAL'],
            ['municipio_id' => 194, 'nombre' => 'PQ. GUANAGUANA'],
            ['municipio_id' => 194, 'nombre' => 'PQ. APARICIO'],
            ['municipio_id' => 194, 'nombre' => 'PQ. TAGUAYA'],
            ['municipio_id' => 194, 'nombre' => 'PQ. EL PINTO'],
            ['municipio_id' => 194, 'nombre' => 'PQ. LA TOSCANA'],
            ['municipio_id' => 195, 'nombre' => 'CM. QUIRIQUIRE'],
            ['municipio_id' => 195, 'nombre' => 'PQ. CACHIPO'],
            ['municipio_id' => 196, 'nombre' => 'CM. BARRANCAS'],
            ['municipio_id' => 196, 'nombre' => 'LOS BARRANCOS DE FAJARDO'],
            ['municipio_id' => 197, 'nombre' => 'CM. AGUASAY'],
            ['municipio_id' => 198, 'nombre' => 'CM. SANTA BARBARA'],
            ['municipio_id' => 199, 'nombre' => 'CM. URACOA'],
            ['municipio_id' => 200, 'nombre' => 'CM. LA ASUNCION'],
            ['municipio_id' => 201, 'nombre' => 'CM. SAN JUAN BAUTISTA'],
            ['municipio_id' => 201, 'nombre' => 'PQ. ZABALA'],
            ['municipio_id' => 202, 'nombre' => 'CM. SANTA ANA'],
            ['municipio_id' => 202, 'nombre' => 'PQ. GUEVARA'],
            ['municipio_id' => 202, 'nombre' => 'PQ. MATASIETE'],
            ['municipio_id' => 202, 'nombre' => 'PQ. BOLIVAR'],
            ['municipio_id' => 202, 'nombre' => 'PQ. SUCRE'],
            ['municipio_id' => 203, 'nombre' => 'CM. PAMPATAR'],
            ['municipio_id' => 203, 'nombre' => 'PQ. AGUIRRE'],
            ['municipio_id' => 204, 'nombre' => 'CM. JUAN GRIEGO'],
            ['municipio_id' => 204, 'nombre' => 'PQ. ADRIAN'],
            ['municipio_id' => 205, 'nombre' => 'CM. PORLAMAR'],
            ['municipio_id' => 206, 'nombre' => 'CM. BOCA DEL RIO'],
            ['municipio_id' => 206, 'nombre' => 'PQ. SAN FRANCISCO'],
            ['municipio_id' => 207, 'nombre' => 'CM. SAN PEDRO DE COCHE'],
            ['municipio_id' => 207, 'nombre' => 'PQ. VICENTE FUENTES'],
            ['municipio_id' => 208, 'nombre' => 'CM. PUNTA DE PIEDRAS'],
            ['municipio_id' => 208, 'nombre' => 'PQ. LOS BARALES'],
            ['municipio_id' => 209, 'nombre' => 'CM. LA PLAZA DE PARAGUACHI'],
            ['municipio_id' => 210, 'nombre' => 'CM. VALLE ESP SANTO'],
            ['municipio_id' => 210, 'nombre' => 'PQ. FRANCISCO FAJARDO'],
            ['municipio_id' => 211, 'nombre' => 'CM. ARAURE'],
            ['municipio_id' => 211, 'nombre' => 'PQ. RIO ACARIGUA'],
            ['municipio_id' => 212, 'nombre' => 'CM. PIRITU'],
            ['municipio_id' => 212, 'nombre' => 'PQ. UVERAL'],
            ['municipio_id' => 213, 'nombre' => 'CM. GUANARE'],
            ['municipio_id' => 213, 'nombre' => 'PQ. CORDOBA'],
            ['municipio_id' => 213, 'nombre' => 'PQ. SAN JUAN GUANAGUANARE'],
            ['municipio_id' => 213, 'nombre' => 'PQ. VIRGEN DE LA COROMOTO'],
            ['municipio_id' => 213, 'nombre' => 'PQ. SAN JOSE DE LA MONTAÑA'],
            ['municipio_id' => 214, 'nombre' => 'CM. GUANARITO'],
            ['municipio_id' => 214, 'nombre' => 'PQ. TRINIDAD DE LA CAPILLA'],
            ['municipio_id' => 214, 'nombre' => 'PQ. DIVINA PASTORA'],
            ['municipio_id' => 215, 'nombre' => 'CM. OSPINO'],
            ['municipio_id' => 215, 'nombre' => 'PQ. APARICION'],
            ['municipio_id' => 215, 'nombre' => 'PQ. LA ESTACION'],
            ['municipio_id' => 216, 'nombre' => 'CM. ACARIGUA'],
            ['municipio_id' => 216, 'nombre' => 'PQ. PAYARA'],
            ['municipio_id' => 216, 'nombre' => 'PQ. PIMPINELA'],
            ['municipio_id' => 216, 'nombre' => 'PQ. RAMON PERAZA'],
            ['municipio_id' => 217, 'nombre' => 'CM. BISCUCUY'],
            ['municipio_id' => 217, 'nombre' => 'PQ. CONCEPCION'],
            ['municipio_id' => 217, 'nombre' => 'PQ. SAN RAFAEL PALO ALZADO'],
            ['municipio_id' => 217, 'nombre' => 'PQ. UVENCIO A VELASQUEZ'],
            ['municipio_id' => 217, 'nombre' => 'PQ. SAN JOSE DE SAGUAZ'],
            ['municipio_id' => 217, 'nombre' => 'PQ. VILLA ROSA'],
            ['municipio_id' => 218, 'nombre' => 'CM. VILLA BRUZUAL'],
            ['municipio_id' => 218, 'nombre' => 'PQ. CANELONES'],
            ['municipio_id' => 218, 'nombre' => 'PQ. SANTA CRUZ'],
            ['municipio_id' => 218, 'nombre' => 'PQ. SAN ISIDRO LABRADOR'],
            ['municipio_id' => 219, 'nombre' => 'CM. CHABASQUEN'],
            ['municipio_id' => 219, 'nombre' => 'PQ. PEÑA BLANCA'],
            ['municipio_id' => 220, 'nombre' => 'CM. AGUA BLANCA'],
            ['municipio_id' => 221, 'nombre' => 'CM. PAPELON'],
            ['municipio_id' => 221, 'nombre' => 'PQ. CAÑO DELGADITO'],
            ['municipio_id' => 222, 'nombre' => 'CM. BOCONOITO'],
            ['municipio_id' => 222, 'nombre' => 'PQ. ANTOLIN TOVAR AQUINO'],
            ['municipio_id' => 223, 'nombre' => 'CM. SAN RAFAEL DE ONOTO'],
            ['municipio_id' => 223, 'nombre' => 'PQ. SANTA FE'],
            ['municipio_id' => 223, 'nombre' => 'PQ. THERMO MORLES'],
            ['municipio_id' => 224, 'nombre' => 'CM. EL PLAYON'],
            ['municipio_id' => 224, 'nombre' => 'PQ. FLORIDA'],
            ['municipio_id' => 225, 'nombre' => 'PQ. RIO CARIBE'],
            ['municipio_id' => 225, 'nombre' => 'PQ. SAN JUAN GALDONAS'],
            ['municipio_id' => 225, 'nombre' => 'PQ. PUERTO SANTO'],
            ['municipio_id' => 225, 'nombre' => 'PQ. EL MORRO DE PTO SANTO'],
            ['municipio_id' => 225, 'nombre' => 'PQ. ANTONIO JOSE DE SUCRE'],
            ['municipio_id' => 226, 'nombre' => 'PQ. EL PILAR'],
            ['municipio_id' => 226, 'nombre' => 'PQ. EL RINCON'],
            ['municipio_id' => 226, 'nombre' => 'PQ. GUARAUNOS'],
            ['municipio_id' => 226, 'nombre' => 'PQ. TUNAPUICITO'],
            ['municipio_id' => 226, 'nombre' => 'PQ. UNION'],
            ['municipio_id' => 226, 'nombre' => 'PQ. GRAL FCO. A VASQUEZ'],
            ['municipio_id' => 227, 'nombre' => 'PQ. SANTA CATALINA'],
            ['municipio_id' => 227, 'nombre' => 'PQ. SANTA ROSA'],
            ['municipio_id' => 227, 'nombre' => 'PQ. SANTA TERESA'],
            ['municipio_id' => 227, 'nombre' => 'PQ. BOLIVAR'],
            ['municipio_id' => 227, 'nombre' => 'PQ. MACARAPANA'],
            ['municipio_id' => 228, 'nombre' => 'PQ. YAGUARAPARO'],
            ['municipio_id' => 228, 'nombre' => 'PQ. LIBERTAD'],
            ['municipio_id' => 228, 'nombre' => 'PQ. PAUJIL'],
            ['municipio_id' => 229, 'nombre' => 'PQ. IRAPA'],
            ['municipio_id' => 229, 'nombre' => 'PQ. CAMPO CLARO'],
            ['municipio_id' => 229, 'nombre' => 'PQ. SORO'],
            ['municipio_id' => 229, 'nombre' => 'PQ. SAN ANTONIO DE IRAPA'],
            ['municipio_id' => 229, 'nombre' => 'PQ. MARABAL'],
            ['municipio_id' => 230, 'nombre' => 'CM. SAN ANT DEL GOLFO'],
            ['municipio_id' => 231, 'nombre' => 'PQ. CUMANACOA'],
            ['municipio_id' => 231, 'nombre' => 'PQ. ARENAS'],
            ['municipio_id' => 231, 'nombre' => 'PQ. ARICAGUA'],
            ['municipio_id' => 231, 'nombre' => 'PQ. COCOLLAR'],
            ['municipio_id' => 231, 'nombre' => 'PQ. SAN FERNANDO'],
            ['municipio_id' => 231, 'nombre' => 'PQ. SAN LORENZO'],
            ['municipio_id' => 232, 'nombre' => 'PQ. CARIACO'],
            ['municipio_id' => 232, 'nombre' => 'PQ. CATUARO'],
            ['municipio_id' => 232, 'nombre' => 'PQ. RENDON'],
            ['municipio_id' => 232, 'nombre' => 'PQ. SANTA CRUZ'],
            ['municipio_id' => 232, 'nombre' => 'PQ. SANTA MARIA'],
            ['municipio_id' => 233, 'nombre' => 'PQ. ALTAGRACIA'],
            ['municipio_id' => 233, 'nombre' => 'PQ. AYACUCHO'],
            ['municipio_id' => 233, 'nombre' => 'PQ. SANTA INES'],
            ['municipio_id' => 233, 'nombre' => 'PQ. VALENTIN VALIENTE'],
            ['municipio_id' => 233, 'nombre' => 'PQ. SAN JUAN'],
            ['municipio_id' => 233, 'nombre' => 'PQ.GRAN MARISCAL'],
            ['municipio_id' => 233, 'nombre' => 'PQ. RAUL LEONI'],
            ['municipio_id' => 234, 'nombre' => 'PQ. GUIRIA'],
            ['municipio_id' => 234, 'nombre' => 'PQ. CRISTOBAL COLON'],
            ['municipio_id' => 234, 'nombre' => 'PQ. PUNTA DE PIEDRA'],
            ['municipio_id' => 234, 'nombre' => 'PQ. BIDEAU'],
            ['municipio_id' => 235, 'nombre' => 'PQ. MARIÑO'],
            ['municipio_id' => 235, 'nombre' => 'PQ. ROMULO GALLEGOS'],
            ['municipio_id' => 236, 'nombre' => 'PQ. TUNAPUY'],
            ['municipio_id' => 236, 'nombre' => 'PQ. CAMPO ELIAS'],
            ['municipio_id' => 237, 'nombre' => 'PQ. SAN JOSE DE AREOCUAR'],
            ['municipio_id' => 237, 'nombre' => 'PQ. TAVERA ACOSTA'],
            ['municipio_id' => 238, 'nombre' => 'CM. MARIGUITAR'],
            ['municipio_id' => 239, 'nombre' => 'PQ. ARAYA'],
            ['municipio_id' => 239, 'nombre' => 'PQ. MANICUARE'],
            ['municipio_id' => 239, 'nombre' => 'PQ. CHACOPATA'],
            ['municipio_id' => 240, 'nombre' => 'CM. COLON'],
            ['municipio_id' => 240, 'nombre' => 'PQ. RIVAS BERTI'],
            ['municipio_id' => 240, 'nombre' => 'PQ. SAN PEDRO DEL RIO'],
            ['municipio_id' => 241, 'nombre' => 'CM. SAN ANT DEL TACHIRA'],
            ['municipio_id' => 241, 'nombre' => 'PQ. PALOTAL'],
            ['municipio_id' => 241, 'nombre' => 'PQ. JUAN VICENTE GOMEZ'],
            ['municipio_id' => 241, 'nombre' => 'PQ. ISAIAS MEDINA ANGARIT'],
            ['municipio_id' => 242, 'nombre' => 'CM. CAPACHO NUEVO'],
            ['municipio_id' => 242, 'nombre' => 'PQ. JUAN GERMAN ROSCIO'],
            ['municipio_id' => 242, 'nombre' => 'PQ. ROMAN CARDENAS'],
            ['municipio_id' => 243, 'nombre' => 'CM. TARIBA'],
            ['municipio_id' => 243, 'nombre' => 'PQ. LA FLORIDA'],
            ['municipio_id' => 243, 'nombre' => 'PQ. AMENODORO RANGEL LAMU'],
            ['municipio_id' => 244, 'nombre' => 'CM. LA GRITA'],
            ['municipio_id' => 244, 'nombre' => 'PQ. EMILIO C. GUERRERO'],
            ['municipio_id' => 244, 'nombre' => 'PQ. MONS. MIGUEL A SALAS'],
            ['municipio_id' => 245, 'nombre' => 'CM. RUBIO'],
            ['municipio_id' => 245, 'nombre' => 'PQ. BRAMON'],
            ['municipio_id' => 245, 'nombre' => 'PQ. LA PETROLEA'],
            ['municipio_id' => 245, 'nombre' => 'PQ. QUINIMARI'],
            ['municipio_id' => 246, 'nombre' => 'CM. LOBATERA'],
            ['municipio_id' => 246, 'nombre' => 'PQ. CONSTITUCION'],
            ['municipio_id' => 247, 'nombre' => 'PQ. LA CONCORDIA'],
            ['municipio_id' => 247, 'nombre' => 'PQ. PEDRO MARIA MORANTES'],
            ['municipio_id' => 247, 'nombre' => 'PQ. SN JUAN BAUTISTA'],
            ['municipio_id' => 247, 'nombre' => 'PQ. SAN SEBASTIAN'],
            ['municipio_id' => 247, 'nombre' => 'PQ. DR. FCO. ROMERO LOBO'],
            ['municipio_id' => 248, 'nombre' => 'CM. PREGONERO'],
            ['municipio_id' => 248, 'nombre' => 'PQ. CARDENAS'],
            ['municipio_id' => 248, 'nombre' => 'PQ. POTOSI'],
            ['municipio_id' => 248, 'nombre' => 'PQ. JUAN PABLO PEÑALOZA'],
            ['municipio_id' => 249, 'nombre' => 'CM. STA. ANA  DEL TACHIRA'],
            ['municipio_id' => 250, 'nombre' => 'CM. LA FRIA'],
            ['municipio_id' => 250, 'nombre' => 'PQ. BOCA DE GRITA'],
            ['municipio_id' => 250, 'nombre' => 'PQ. JOSE ANTONIO PAEZ'],
            ['municipio_id' => 251, 'nombre' => 'CM. PALMIRA'],
            ['municipio_id' => 252, 'nombre' => 'CM. MICHELENA'],
            ['municipio_id' => 253, 'nombre' => 'CM. ABEJALES'],
            ['municipio_id' => 253, 'nombre' => 'PQ. SAN JOAQUIN DE NAVAY'],
            ['municipio_id' => 253, 'nombre' => 'PQ. DORADAS'],
            ['municipio_id' => 253, 'nombre' => 'PQ. EMETERIO OCHOA'],
            ['municipio_id' => 254, 'nombre' => 'CM. COLONCITO'],
            ['municipio_id' => 254, 'nombre' => 'PQ. LA PALMITA'],
            ['municipio_id' => 255, 'nombre' => 'CM. UREÑA'],
            ['municipio_id' => 255, 'nombre' => 'PQ. NUEVA ARCADIA'],
            ['municipio_id' => 256, 'nombre' => 'CM. QUENIQUEA'],
            ['municipio_id' => 256, 'nombre' => 'PQ. SAN PABLO'],
            ['municipio_id' => 256, 'nombre' => 'PQ.ELEAZAR LOPEZ CONTRERA'],
            ['municipio_id' => 257, 'nombre' => 'CM. CORDERO'],
            ['municipio_id' => 258, 'nombre' => 'CM.SAN RAFAEL DEL PINAL'],
            ['municipio_id' => 258, 'nombre' => 'PQ. SANTO DOMINGO'],
            ['municipio_id' => 258, 'nombre' => 'PQ. ALBERTO ADRIANI'],
            ['municipio_id' => 259, 'nombre' => 'CM. CAPACHO VIEJO'],
            ['municipio_id' => 259, 'nombre' => 'PQ. CIPRIANO CASTRO'],
            ['municipio_id' => 259, 'nombre' => 'PQ. MANUEL FELIPE RUGELES'],
            ['municipio_id' => 260, 'nombre' => 'CM. LA TENDIDA'],
            ['municipio_id' => 260, 'nombre' => 'PQ. BOCONO'],
            ['municipio_id' => 260, 'nombre' => 'PQ. HERNANDEZ'],
            ['municipio_id' => 261, 'nombre' => 'CM. SEBORUCO'],
            ['municipio_id' => 262, 'nombre' => 'CM. LAS MESAS'],
            ['municipio_id' => 263, 'nombre' => 'CM. SAN JOSE DE BOLIVAR'],
            ['municipio_id' => 264, 'nombre' => 'CM. EL COBRE'],
            ['municipio_id' => 265, 'nombre' => 'CM. DELICIAS'],
            ['municipio_id' => 266, 'nombre' => 'CM. SAN SIMON'],
            ['municipio_id' => 267, 'nombre' => 'CM. SAN JOSECITO'],
            ['municipio_id' => 268, 'nombre' => 'CM. UMUQUENA'],
            ['municipio_id' => 269, 'nombre' => 'PQ. BETIJOQUE'],
            ['municipio_id' => 269, 'nombre' => 'PQ. JOSE G HERNANDEZ'],
            ['municipio_id' => 269, 'nombre' => 'PQ. LA PUEBLITA'],
            ['municipio_id' => 269, 'nombre' => 'PQ. EL CEDRO'],
            ['municipio_id' => 270, 'nombre' => 'PQ. BOCONO'],
            ['municipio_id' => 270, 'nombre' => 'PQ. EL CARMEN'],
            ['municipio_id' => 270, 'nombre' => 'PQ. MOSQUEY'],
            ['municipio_id' => 270, 'nombre' => 'PQ. AYACUCHO'],
            ['municipio_id' => 270, 'nombre' => 'PQ. BURBUSAY'],
            ['municipio_id' => 270, 'nombre' => 'PQ. GENERAL RIVAS'],
            ['municipio_id' => 270, 'nombre' => 'PQ. MONSEÑOR JAUREGUI'],
            ['municipio_id' => 270, 'nombre' => 'PQ. RAFAEL RANGEL'],
            ['municipio_id' => 270, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 270, 'nombre' => 'PQ. SAN MIGUEL'],
            ['municipio_id' => 270, 'nombre' => 'PQ. GUARAMACAL'],
            ['municipio_id' => 270, 'nombre' => 'PQ. LA VEGA DE GUARAMACAL'],
            ['municipio_id' => 271, 'nombre' => 'PQ. CARACHE'],
            ['municipio_id' => 271, 'nombre' => 'PQ. LA CONCEPCION'],
            ['municipio_id' => 271, 'nombre' => 'PQ. CUICAS'],
            ['municipio_id' => 271, 'nombre' => 'PQ. PANAMERICANA'],
            ['municipio_id' => 271, 'nombre' => 'PQ. SANTA CRUZ'],
            ['municipio_id' => 272, 'nombre' => 'PQ. ESCUQUE'],
            ['municipio_id' => 272, 'nombre' => 'PQ. SABANA LIBRE'],
            ['municipio_id' => 272, 'nombre' => 'PQ. LA UNION'],
            ['municipio_id' => 272, 'nombre' => 'PQ. SANTA RITA'],
            ['municipio_id' => 273, 'nombre' => 'PQ. CRISTOBAL MENDOZA'],
            ['municipio_id' => 273, 'nombre' => 'PQ. CHIQUINQUIRA'],
            ['municipio_id' => 273, 'nombre' => 'PQ. MATRIZ'],
            ['municipio_id' => 273, 'nombre' => 'PQ. MONSEÑOR CARRILLO'],
            ['municipio_id' => 273, 'nombre' => 'PQ. CRUZ CARRILLO'],
            ['municipio_id' => 273, 'nombre' => 'PQ. ANDRES LINARES'],
            ['municipio_id' => 273, 'nombre' => 'PQ. TRES ESQUINAS'],
            ['municipio_id' => 274, 'nombre' => 'PQ. LA QUEBRADA'],
            ['municipio_id' => 274, 'nombre' => 'PQ. JAJO'],
            ['municipio_id' => 274, 'nombre' => 'PQ. LA MESA'],
            ['municipio_id' => 274, 'nombre' => 'PQ. SANTIAGO'],
            ['municipio_id' => 274, 'nombre' => 'PQ. CABIMBU'],
            ['municipio_id' => 274, 'nombre' => 'PQ. TUÑAME'],
            ['municipio_id' => 275, 'nombre' => 'PQ. MERCEDES DIAZ'],
            ['municipio_id' => 275, 'nombre' => 'PQ. JUAN IGNACIO MONTILLA'],
            ['municipio_id' => 275, 'nombre' => 'PQ. LA BEATRIZ'],
            ['municipio_id' => 275, 'nombre' => 'PQ. MENDOZA'],
            ['municipio_id' => 275, 'nombre' => 'PQ. LA PUERTA'],
            ['municipio_id' => 275, 'nombre' => 'PQ. SAN LUIS'],
            ['municipio_id' => 276, 'nombre' => 'PQ. CHEJENDE'],
            ['municipio_id' => 276, 'nombre' => 'PQ. CARRILLO'],
            ['municipio_id' => 276, 'nombre' => 'PQ. CEGARRA'],
            ['municipio_id' => 276, 'nombre' => 'PQ. BOLIVIA'],
            ['municipio_id' => 276, 'nombre' => 'PQ. MANUEL SALVADOR ULLOA'],
            ['municipio_id' => 276, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 276, 'nombre' => 'PQ. ARNOLDO GABALDON'],
            ['municipio_id' => 277, 'nombre' => 'PQ. EL DIVIDIVE'],
            ['municipio_id' => 277, 'nombre' => 'PQ. AGUA CALIENTE'],
            ['municipio_id' => 277, 'nombre' => 'PQ. EL CENIZO'],
            ['municipio_id' => 277, 'nombre' => 'PQ. AGUA SANTA'],
            ['municipio_id' => 277, 'nombre' => 'PQ. VALERITA'],
            ['municipio_id' => 278, 'nombre' => 'PQ. MONTE CARMELO'],
            ['municipio_id' => 278, 'nombre' => 'PQ. BUENA VISTA'],
            ['municipio_id' => 278, 'nombre' => 'PQ. STA MARIA DEL HORCON'],
            ['municipio_id' => 279, 'nombre' => 'PQ. MOTATAN'],
            ['municipio_id' => 279, 'nombre' => 'PQ. EL BAÑO'],
            ['municipio_id' => 279, 'nombre' => 'PQ. JALISCO'],
            ['municipio_id' => 280, 'nombre' => 'PQ. PAMPAN'],
            ['municipio_id' => 280, 'nombre' => 'PQ. SANTA ANA'],
            ['municipio_id' => 280, 'nombre' => 'PQ. LA PAZ'],
            ['municipio_id' => 280, 'nombre' => 'PQ. FLOR DE PATRIA'],
            ['municipio_id' => 281, 'nombre' => 'PQ. CARVAJAL'],
            ['municipio_id' => 281, 'nombre' => 'PQ. ANTONIO N BRICEÑO'],
            ['municipio_id' => 281, 'nombre' => 'PQ. CAMPO ALEGRE'],
            ['municipio_id' => 281, 'nombre' => 'PQ. JOSE LEONARDO SUAREZ'],
            ['municipio_id' => 282, 'nombre' => 'PQ. SABANA DE MENDOZA'],
            ['municipio_id' => 282, 'nombre' => 'PQ. JUNIN'],
            ['municipio_id' => 282, 'nombre' => 'PQ. VALMORE RODRIGUEZ'],
            ['municipio_id' => 282, 'nombre' => 'PQ. EL PARAISO'],
            ['municipio_id' => 283, 'nombre' => 'PQ. SANTA ISABEL'],
            ['municipio_id' => 283, 'nombre' => 'PQ. ARAGUANEY'],
            ['municipio_id' => 283, 'nombre' => 'PQ. EL JAGUITO'],
            ['municipio_id' => 283, 'nombre' => 'PQ. LA ESPERANZA'],
            ['municipio_id' => 284, 'nombre' => 'PQ. SABANA GRANDE'],
            ['municipio_id' => 284, 'nombre' => 'PQ. CHEREGUE'],
            ['municipio_id' => 284, 'nombre' => 'PQ. GRANADOS'],
            ['municipio_id' => 285, 'nombre' => 'PQ. EL SOCORRO'],
            ['municipio_id' => 285, 'nombre' => 'PQ. LOS CAPRICHOS'],
            ['municipio_id' => 285, 'nombre' => 'PQ. ANTONIO JOSE DE SUCRE'],
            ['municipio_id' => 286, 'nombre' => 'PQ. CAMPO ELIAS'],
            ['municipio_id' => 286, 'nombre' => 'PQ. ARNOLDO GABALDON'],
            ['municipio_id' => 287, 'nombre' => 'PQ. SANTA APOLONIA'],
            ['municipio_id' => 287, 'nombre' => 'PQ. LA CEIBA'],
            ['municipio_id' => 287, 'nombre' => 'PQ. EL PROGRESO'],
            ['municipio_id' => 287, 'nombre' => 'PQ. TRES DE FEBRERO'],
            ['municipio_id' => 288, 'nombre' => 'PQ. PAMPANITO'],
            ['municipio_id' => 288, 'nombre' => 'PQ. PAMPANITO II'],
            ['municipio_id' => 288, 'nombre' => 'PQ. LA CONCEPCION'],
            ['municipio_id' => 289, 'nombre' => 'CM. AROA'],
            ['municipio_id' => 290, 'nombre' => 'CM. CHIVACOA'],
            ['municipio_id' => 290, 'nombre' => 'PQ. CAMPO ELIAS'],
            ['municipio_id' => 291, 'nombre' => 'CM. NIRGUA'],
            ['municipio_id' => 291, 'nombre' => 'PQ. SALOM'],
            ['municipio_id' => 291, 'nombre' => 'PQ. TEMERLA'],
            ['municipio_id' => 292, 'nombre' => 'CM. SAN FELIPE'],
            ['municipio_id' => 292, 'nombre' => 'PQ. ALBARICO'],
            ['municipio_id' => 292, 'nombre' => 'PQ. SAN JAVIER'],
            ['municipio_id' => 293, 'nombre' => 'CM. GUAMA'],
            ['municipio_id' => 294, 'nombre' => 'CM. URACHICHE'],
            ['municipio_id' => 295, 'nombre' => 'CM. YARITAGUA'],
            ['municipio_id' => 295, 'nombre' => 'PQ. SAN ANDRES'],
            ['municipio_id' => 296, 'nombre' => 'CM. SABANA DE PARRA'],
            ['municipio_id' => 297, 'nombre' => 'CM. BORAURE'],
            ['municipio_id' => 298, 'nombre' => 'CM. COCOROTE'],
            ['municipio_id' => 299, 'nombre' => 'CM. INDEPENDENCIA'],
            ['municipio_id' => 300, 'nombre' => 'CM. SAN PABLO'],
            ['municipio_id' => 301, 'nombre' => 'CM. YUMARE'],
            ['municipio_id' => 302, 'nombre' => 'CM. FARRIAR'],
            ['municipio_id' => 302, 'nombre' => 'PQ. EL GUAYABO'],
            ['municipio_id' => 303, 'nombre' => 'PQ. GENERAL URDANETA'],
            ['municipio_id' => 303, 'nombre' => 'PQ. LIBERTADOR'],
            ['municipio_id' => 303, 'nombre' => 'PQ. MANUEL GUANIPA MATOS'],
            ['municipio_id' => 303, 'nombre' => 'PQ. MARCELINO BRICEÑO'],
            ['municipio_id' => 303, 'nombre' => 'PQ. SAN TIMOTEO'],
            ['municipio_id' => 303, 'nombre' => 'PQ. PUEBLO NUEVO'],
            ['municipio_id' => 304, 'nombre' => 'PQ. PEDRO LUCAS URRIBARRI'],
            ['municipio_id' => 304, 'nombre' => 'PQ. SANTA RITA'],
            ['municipio_id' => 304, 'nombre' => 'PQ. JOSE CENOVIO URRIBARR'],
            ['municipio_id' => 304, 'nombre' => 'PQ. EL MENE'],
            ['municipio_id' => 305, 'nombre' => 'PQ. SANTA CRUZ DEL ZULIA'],
            ['municipio_id' => 305, 'nombre' => 'PQ. URRIBARRI'],
            ['municipio_id' => 305, 'nombre' => 'PQ. MORALITO'],
            ['municipio_id' => 305, 'nombre' => 'PQ. SAN CARLOS DEL ZULIA'],
            ['municipio_id' => 305, 'nombre' => 'PQ. SANTA BARBARA'],
            ['municipio_id' => 306, 'nombre' => 'PQ. LUIS DE VICENTE'],
            ['municipio_id' => 306, 'nombre' => 'PQ. RICAURTE'],
            ['municipio_id' => 306, 'nombre' => 'PQ. MONS.MARCOS SERGIO G'],
            ['municipio_id' => 306, 'nombre' => 'PQ. SAN RAFAEL'],
            ['municipio_id' => 306, 'nombre' => 'PQ. LAS PARCELAS'],
            ['municipio_id' => 306, 'nombre' => 'PQ. TAMARE'],
            ['municipio_id' => 306, 'nombre' => 'PQ. LA SIERRITA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. BOLIVAR'],
            ['municipio_id' => 307, 'nombre' => 'PQ. COQUIVACOA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. CRISTO DE ARANZA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. CHIQUINQUIRA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. SANTA LUCIA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. OLEGARIO VILLALOBOS'],
            ['municipio_id' => 307, 'nombre' => 'PQ. JUANA DE AVILA'],
            ['municipio_id' => 307, 'nombre' => 'PQ.CARACCIOLO PARRA PEREZ'],
            ['municipio_id' => 307, 'nombre' => 'PQ. IDELFONZO VASQUEZ'],
            ['municipio_id' => 307, 'nombre' => 'PQ. CACIQUE MARA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. CECILIO ACOSTA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. RAUL LEONI'],
            ['municipio_id' => 307, 'nombre' => 'PQ. FRANCISCO EUGENIO B'],
            ['municipio_id' => 307, 'nombre' => 'PQ. MANUEL DAGNINO'],
            ['municipio_id' => 307, 'nombre' => 'PQ. LUIS HURTADO HIGUERA'],
            ['municipio_id' => 307, 'nombre' => 'PQ. VENANCIO PULGAR'],
            ['municipio_id' => 307, 'nombre' => 'PQ. ANTONIO BORJAS ROMERO'],
            ['municipio_id' => 307, 'nombre' => 'PQ. SAN ISIDRO'],
            ['municipio_id' => 308, 'nombre' => 'PQ. FARIA'],
            ['municipio_id' => 308, 'nombre' => 'PQ. SAN ANTONIO'],
            ['municipio_id' => 308, 'nombre' => 'PQ. ANA MARIA CAMPOS'],
            ['municipio_id' => 308, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 308, 'nombre' => 'PQ. ALTAGRACIA'],
            ['municipio_id' => 309, 'nombre' => 'PQ. GUAJIRA'],
            ['municipio_id' => 309, 'nombre' => 'PQ. ELIAS SANCHEZ RUBIO'],
            ['municipio_id' => 309, 'nombre' => 'PQ. SINAMAICA'],
            ['municipio_id' => 309, 'nombre' => 'PQ. ALTA GUAJIRA'],
            ['municipio_id' => 310, 'nombre' => 'PQ. SAN JOSE DE PERIJA'],
            ['municipio_id' => 310, 'nombre' => 'PQ.BARTOLOME DE LAS CASAS'],
            ['municipio_id' => 310, 'nombre' => 'PQ. LIBERTAD'],
            ['municipio_id' => 310, 'nombre' => 'PQ. RIO NEGRO'],
            ['municipio_id' => 311, 'nombre' => 'PQ. GIBRALTAR'],
            ['municipio_id' => 311, 'nombre' => 'PQ. HERAS'],
            ['municipio_id' => 311, 'nombre' => 'PQ. M.ARTURO CELESTINO A'],
            ['municipio_id' => 311, 'nombre' => 'PQ. ROMULO GALLEGOS'],
            ['municipio_id' => 311, 'nombre' => 'PQ. BOBURES'],
            ['municipio_id' => 311, 'nombre' => 'PQ. EL BATEY'],
            ['municipio_id' => 312, 'nombre' => 'PQ. ANDRES BELLO (KM 48)'],
            ['municipio_id' => 312, 'nombre' => 'PQ. POTRERITOS'],
            ['municipio_id' => 312, 'nombre' => 'PQ. EL CARMELO'],
            ['municipio_id' => 312, 'nombre' => 'PQ. CHIQUINQUIRA'],
            ['municipio_id' => 312, 'nombre' => 'PQ. CONCEPCION'],
            ['municipio_id' => 313, 'nombre' => 'PQ. ELEAZAR LOPEZ C'],
            ['municipio_id' => 313, 'nombre' => 'PQ. ALONSO DE OJEDA'],
            ['municipio_id' => 313, 'nombre' => 'PQ. VENEZUELA'],
            ['municipio_id' => 313, 'nombre' => 'PQ. CAMPO LARA'],
            ['municipio_id' => 313, 'nombre' => 'PQ. LIBERTAD'],
            ['municipio_id' => 314, 'nombre' => 'PQ. UDON PEREZ'],
            ['municipio_id' => 314, 'nombre' => 'PQ. ENCONTRADOS'],
            ['municipio_id' => 315, 'nombre' => 'PQ. DONALDO GARCIA'],
            ['municipio_id' => 315, 'nombre' => 'PQ. SIXTO ZAMBRANO'],
            ['municipio_id' => 315, 'nombre' => 'PQ. EL ROSARIO'],
            ['municipio_id' => 316, 'nombre' => 'PQ. AMBROSIO'],
            ['municipio_id' => 316, 'nombre' => 'PQ. GERMAN RIOS LINARES'],
            ['municipio_id' => 316, 'nombre' => 'PQ. JORGE HERNANDEZ'],
            ['municipio_id' => 316, 'nombre' => 'PQ. LA ROSA'],
            ['municipio_id' => 316, 'nombre' => 'PQ. PUNTA GORDA'],
            ['municipio_id' => 316, 'nombre' => 'PQ. CARMEN HERRERA'],
            ['municipio_id' => 316, 'nombre' => 'PQ. SAN BENITO'],
            ['municipio_id' => 316, 'nombre' => 'PQ. ROMULO BETANCOURT'],
            ['municipio_id' => 316, 'nombre' => 'PQ. ARISTIDES CALVANI'],
            ['municipio_id' => 317, 'nombre' => 'PQ. RAUL CUENCA'],
            ['municipio_id' => 317, 'nombre' => 'PQ. LA VICTORIA'],
            ['municipio_id' => 317, 'nombre' => 'PQ. RAFAEL URDANETA'],
            ['municipio_id' => 318, 'nombre' => 'PQ. JOSE RAMON YEPEZ'],
            ['municipio_id' => 318, 'nombre' => 'PQ. LA CONCEPCION'],
            ['municipio_id' => 318, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 318, 'nombre' => 'PQ. MARIANO PARRA LEON'],
            ['municipio_id' => 319, 'nombre' => 'PQ. MONAGAS'],
            ['municipio_id' => 319, 'nombre' => 'PQ. ISLA DE TOAS'],
            ['municipio_id' => 320, 'nombre' => 'PQ. MARCIAL HERNANDEZ'],
            ['municipio_id' => 320, 'nombre' => 'PQ. FRANCISCO OCHOA'],
            ['municipio_id' => 320, 'nombre' => 'PQ. SAN FRANCISCO'],
            ['municipio_id' => 320, 'nombre' => 'PQ. EL BAJO'],
            ['municipio_id' => 320, 'nombre' => 'PQ. DOMITILA FLORES'],
            ['municipio_id' => 320, 'nombre' => 'PQ. LOS CORTIJOS'],
            ['municipio_id' => 321, 'nombre' => 'PQ. BARI'],
            ['municipio_id' => 321, 'nombre' => 'PQ. JESUS M SEMPRUN'],
            ['municipio_id' => 322, 'nombre' => 'PQ. SIMON RODRIGUEZ'],
            ['municipio_id' => 322, 'nombre' => 'PQ. CARLOS QUEVEDO'],
            ['municipio_id' => 322, 'nombre' => 'PQ. FRANCISCO J PULGAR'],
            ['municipio_id' => 323, 'nombre' => 'PQ. RAFAEL MARIA BARALT'],
            ['municipio_id' => 323, 'nombre' => 'PQ. MANUEL MANRIQUE'],
            ['municipio_id' => 323, 'nombre' => 'PQ. RAFAEL URDANETA'],
            ['municipio_id' => 324, 'nombre' => 'PQ. FERNANDO GIRON TOVAR'],
            ['municipio_id' => 324, 'nombre' => 'PQ. LUIS ALBERTO GOMEZ'],
            ['municipio_id' => 324, 'nombre' => 'PQ. PARHUEÑA'],
            ['municipio_id' => 324, 'nombre' => 'PQ. PLATANILLAL'],
            ['municipio_id' => 325, 'nombre' => 'CM. SAN FERNANDO DE ATABA'],
            ['municipio_id' => 325, 'nombre' => 'PQ. UCATA'],
            ['municipio_id' => 325, 'nombre' => 'PQ. YAPACANA'],
            ['municipio_id' => 325, 'nombre' => 'PQ. CANAME'],
            ['municipio_id' => 326, 'nombre' => 'CM. MAROA'],
            ['municipio_id' => 326, 'nombre' => 'PQ. VICTORINO'],
            ['municipio_id' => 326, 'nombre' => 'PQ. COMUNIDAD'],
            ['municipio_id' => 327, 'nombre' => 'CM. SAN CARLOS DE RIO NEG'],
            ['municipio_id' => 327, 'nombre' => 'PQ. SOLANO'],
            ['municipio_id' => 327, 'nombre' => 'PQ. CASIQUIARE'],
            ['municipio_id' => 327, 'nombre' => 'PQ. COCUY'],
            ['municipio_id' => 328, 'nombre' => 'CM. ISLA DE RATON'],
            ['municipio_id' => 328, 'nombre' => 'PQ. SAMARIAPO'],
            ['municipio_id' => 328, 'nombre' => 'PQ. SIPAPO'],
            ['municipio_id' => 328, 'nombre' => 'PQ. MUNDUAPO'],
            ['municipio_id' => 328, 'nombre' => 'PQ. GUAYAPO'],
            ['municipio_id' => 329, 'nombre' => 'CM. SAN JUAN DE MANAPIARE'],
            ['municipio_id' => 329, 'nombre' => 'PQ. ALTO VENTUARI'],
            ['municipio_id' => 329, 'nombre' => 'PQ. MEDIO VENTUARI'],
            ['municipio_id' => 329, 'nombre' => 'PQ. BAJO VENTUARI'],
            ['municipio_id' => 330, 'nombre' => 'CM. LA ESMERALDA'],
            ['municipio_id' => 330, 'nombre' => 'PQ. HUACHAMACARE'],
            ['municipio_id' => 330, 'nombre' => 'PQ. MARAWAKA'],
            ['municipio_id' => 330, 'nombre' => 'PQ. MAVACA'],
            ['municipio_id' => 330, 'nombre' => 'PQ. SIERRA PARIMA'],
            ['municipio_id' => 331, 'nombre' => 'PQ. SAN JOSE'],
            ['municipio_id' => 331, 'nombre' => 'PQ. VIRGEN DEL VALLE'],
            ['municipio_id' => 331, 'nombre' => 'PQ. SAN RAFAEL'],
            ['municipio_id' => 331, 'nombre' => 'PQ. JOSE VIDAL MARCANO'],
            ['municipio_id' => 331, 'nombre' => 'PQ. LEONARDO RUIZ PINEDA'],
            ['municipio_id' => 331, 'nombre' => 'PQ. MONS. ARGIMIRO GARCIA'],
            ['municipio_id' => 331, 'nombre' => 'PQ.MCL.ANTONIO J DE SUCRE'],
            ['municipio_id' => 331, 'nombre' => 'PQ. JUAN MILLAN'],
            ['municipio_id' => 332, 'nombre' => 'PQ. PEDERNALES'],
            ['municipio_id' => 332, 'nombre' => 'PQ. LUIS B PRIETO FIGUERO'],
            ['municipio_id' => 333, 'nombre' => 'PQ. CURIAPO'],
            ['municipio_id' => 333, 'nombre' => 'PQ. SANTOS DE ABELGAS'],
            ['municipio_id' => 333, 'nombre' => 'PQ. MANUEL RENAUD'],
            ['municipio_id' => 333, 'nombre' => 'PQ. PADRE BARRAL'],
            ['municipio_id' => 333, 'nombre' => 'PQ. ANICETO LUGO'],
            ['municipio_id' => 333, 'nombre' => 'PQ. ALMIRANTE LUIS BRION'],
            ['municipio_id' => 334, 'nombre' => 'PQ. IMATACA'],
            ['municipio_id' => 334, 'nombre' => 'PQ. ROMULO GALLEGOS'],
            ['municipio_id' => 334, 'nombre' => 'PQ. JUAN BAUTISTA ARISMEN'],
            ['municipio_id' => 334, 'nombre' => 'PQ. MANUEL PIAR'],
            ['municipio_id' => 334, 'nombre' => 'PQ. 5 DE JULIO'],
            ['municipio_id' => 335, 'nombre' => 'PQ. CARABALLEDA'],
            ['municipio_id' => 335, 'nombre' => 'PQ. CARAYACA'],
            ['municipio_id' => 335, 'nombre' => 'PQ. CARUAO'],
            ['municipio_id' => 335, 'nombre' => 'PQ. CATIA LA MAR'],
            ['municipio_id' => 335, 'nombre' => 'PQ. LA GUAIRA'],
            ['municipio_id' => 335, 'nombre' => 'PQ. MACUTO'],
            ['municipio_id' => 335, 'nombre' => 'PQ. MAIQUETIA'],
            ['municipio_id' => 335, 'nombre' => 'PQ. NAIGUATA'],
            ['municipio_id' => 335, 'nombre' => 'PQ. EL JUNKO'],
            ['municipio_id' => 335, 'nombre' => 'PQ. URIMARE'],
            ['municipio_id' => 335, 'nombre' => 'PQ. CARLOS SOUBLETTE'],
        ];
        foreach ($parroquias as $parroquia) {
            Parroquia::create($parroquia);
        }
    }

}
